import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInMalmesburyWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Malmesbury Wiltshire"
      description="Professional emergency roofing services in Malmesbury Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Malmesbury Wiltshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInMalmesburyWiltshire;
