import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInPetworthWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Petworth West Sussex"
      description="Professional emergency roofing services in Petworth West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Petworth West Sussex"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInPetworthWestSussex;
