import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInFleetHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Fleet Hampshire"
      description="Professional emergency roofing services in Fleet Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Fleet Hampshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInFleetHampshire;
