import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInChalfontStPeterBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Chalfont St Peter Buckinghamshire"
      description="Professional emergency roofing services in Chalfont St Peter Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Chalfont St Peter Buckinghamshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInChalfontStPeterBuckinghamshire;
