import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInAmershamBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Amersham Buckinghamshire"
      description="Professional emergency roofing services in Amersham Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Amersham Buckinghamshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInAmershamBuckinghamshire;
