import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInAltonHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Alton Hampshire"
      description="Professional emergency roofing services in Alton Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Alton Hampshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInAltonHampshire;
