import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInHorleySurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Horley Surrey"
      description="Professional emergency roofing services in Horley Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Horley Surrey"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInHorleySurrey;
