import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInStonehouseGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Stonehouse Gloucestershire"
      description="Professional emergency roofing services in Stonehouse Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Stonehouse Gloucestershire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInStonehouseGloucestershire;
