import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInGuildfordSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Guildford Surrey"
      description="Professional emergency roofing services in Guildford Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Guildford Surrey"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInGuildfordSurrey;
