import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInWestburyWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Westbury Wiltshire"
      description="Professional emergency roofing services in Westbury Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Westbury Wiltshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInWestburyWiltshire;
