import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInBerkeleyGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Berkeley Gloucestershire"
      description="Professional emergency roofing services in Berkeley Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Berkeley Gloucestershire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInBerkeleyGloucestershire;
