import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInGloucesterGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Gloucester Gloucestershire"
      description="Professional emergency roofing services in Gloucester Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Gloucester Gloucestershire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInGloucesterGloucestershire;
