import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInDidcotOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Didcot Oxfordshire"
      description="Professional emergency roofing services in Didcot Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Didcot Oxfordshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInDidcotOxfordshire;
