import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInFarnhamSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Farnham Surrey"
      description="Professional emergency roofing services in Farnham Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Farnham Surrey"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInFarnhamSurrey;
