import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInDursleyGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Dursley Gloucestershire"
      description="Professional emergency roofing services in Dursley Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Dursley Gloucestershire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInDursleyGloucestershire;
