import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInCharlburyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Charlbury Oxfordshire"
      description="Professional emergency roofing services in Charlbury Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Charlbury Oxfordshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInCharlburyOxfordshire;
