import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInSelseyWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Selsey West Sussex"
      description="Professional emergency roofing services in Selsey West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Selsey West Sussex"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInSelseyWestSussex;
