import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInCrawleyWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Crawley West Sussex"
      description="Professional emergency roofing services in Crawley West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Crawley West Sussex"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInCrawleyWestSussex;
