import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInFarnboroughHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Farnborough Hampshire"
      description="Professional emergency roofing services in Farnborough Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Farnborough Hampshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInFarnboroughHampshire;
