import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInWorthingWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Worthing West Sussex"
      description="Professional emergency roofing services in Worthing West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Worthing West Sussex"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInWorthingWestSussex;
