import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInCowleyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Cowley Oxfordshire"
      description="Professional emergency roofing services in Cowley Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Cowley Oxfordshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInCowleyOxfordshire;
