import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInHaywardsHeathWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Haywards Heath West Sussex"
      description="Professional emergency roofing services in Haywards Heath West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Haywards Heath West Sussex"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInHaywardsHeathWestSussex;
