import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInCalneWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Calne Wiltshire"
      description="Professional emergency roofing services in Calne Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Calne Wiltshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInCalneWiltshire;
