import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInMarlboroughWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Marlborough Wiltshire"
      description="Professional emergency roofing services in Marlborough Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Marlborough Wiltshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInMarlboroughWiltshire;
