import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInStowOnTheWoldGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Stow On The Wold Gloucestershire"
      description="Professional emergency roofing services in Stow On The Wold Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Stow On The Wold Gloucestershire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInStowOnTheWoldGloucestershire;
