import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInAbingdonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Abingdon Oxfordshire"
      description="Professional emergency roofing services in Abingdon Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Abingdon Oxfordshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInAbingdonOxfordshire;
