import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInJerichoOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Jericho Oxfordshire"
      description="Professional emergency roofing services in Jericho Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Jericho Oxfordshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInJerichoOxfordshire;
