import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInBlackbirdLeysOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Blackbird Leys Oxfordshire"
      description="Professional emergency roofing services in Blackbird Leys Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Blackbird Leys Oxfordshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInBlackbirdLeysOxfordshire;
