import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInSouthamptonHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Southampton Hampshire"
      description="Professional emergency roofing services in Southampton Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Southampton Hampshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInSouthamptonHampshire;
