import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInTidworthWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Tidworth Wiltshire"
      description="Professional emergency roofing services in Tidworth Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Tidworth Wiltshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInTidworthWiltshire;
