import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInMarstonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Marston Oxfordshire"
      description="Professional emergency roofing services in Marston Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Marston Oxfordshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInMarstonOxfordshire;
