import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInAndoverHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Andover Hampshire"
      description="Professional emergency roofing services in Andover Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Andover Hampshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInAndoverHampshire;
