import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInGreatMissendenBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Great Missenden Buckinghamshire"
      description="Professional emergency roofing services in Great Missenden Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Great Missenden Buckinghamshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInGreatMissendenBuckinghamshire;
