import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInChichesterWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Chichester West Sussex"
      description="Professional emergency roofing services in Chichester West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Chichester West Sussex"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInChichesterWestSussex;
