import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInWolvercoteOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Wolvercote Oxfordshire"
      description="Professional emergency roofing services in Wolvercote Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Wolvercote Oxfordshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInWolvercoteOxfordshire;
