import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInAldershotHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Aldershot Hampshire"
      description="Professional emergency roofing services in Aldershot Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Aldershot Hampshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInAldershotHampshire;
