import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInHaslemereSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Haslemere Surrey"
      description="Professional emergency roofing services in Haslemere Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Haslemere Surrey"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInHaslemereSurrey;
