import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInEpsomSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Epsom Surrey"
      description="Professional emergency roofing services in Epsom Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Epsom Surrey"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInEpsomSurrey;
