import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInWendoverBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Wendover Buckinghamshire"
      description="Professional emergency roofing services in Wendover Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Wendover Buckinghamshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInWendoverBuckinghamshire;
