import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInTottonHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Totton Hampshire"
      description="Professional emergency roofing services in Totton Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Totton Hampshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInTottonHampshire;
