import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInPewseyWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Pewsey Wiltshire"
      description="Professional emergency roofing services in Pewsey Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Pewsey Wiltshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInPewseyWiltshire;
