import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInCartertonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Carterton Oxfordshire"
      description="Professional emergency roofing services in Carterton Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Carterton Oxfordshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInCartertonOxfordshire;
