import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInTewkesburyGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Tewkesbury Gloucestershire"
      description="Professional emergency roofing services in Tewkesbury Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Tewkesbury Gloucestershire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInTewkesburyGloucestershire;
