import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInWinslowBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Winslow Buckinghamshire"
      description="Professional emergency roofing services in Winslow Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Winslow Buckinghamshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInWinslowBuckinghamshire;
