import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInKidlingtonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Kidlington Oxfordshire"
      description="Professional emergency roofing services in Kidlington Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Kidlington Oxfordshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInKidlingtonOxfordshire;
