import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInRingwoodHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Ringwood Hampshire"
      description="Professional emergency roofing services in Ringwood Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Ringwood Hampshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInRingwoodHampshire;
