import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInWokinghamBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Wokingham Berkshire"
      description="Professional emergency roofing services in Wokingham Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Wokingham Berkshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInWokinghamBerkshire;
