import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInArundelWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Arundel West Sussex"
      description="Professional emergency roofing services in Arundel West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Arundel West Sussex"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInArundelWestSussex;
