import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInAmesburyWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Amesbury Wiltshire"
      description="Professional emergency roofing services in Amesbury Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Amesbury Wiltshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInAmesburyWiltshire;
