import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInMaidenheadBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Maidenhead Berkshire"
      description="Professional emergency roofing services in Maidenhead Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Maidenhead Berkshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInMaidenheadBerkshire;
