import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInGodalmingSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Godalming Surrey"
      description="Professional emergency roofing services in Godalming Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Godalming Surrey"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInGodalmingSurrey;
