import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInOxfordOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Oxford Oxfordshire"
      description="Professional emergency roofing services in Oxford Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Oxford Oxfordshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInOxfordOxfordshire;
