import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInGerrardsCrossBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Gerrards Cross Buckinghamshire"
      description="Professional emergency roofing services in Gerrards Cross Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Gerrards Cross Buckinghamshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInGerrardsCrossBuckinghamshire;
