import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInWeybridgeSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Weybridge Surrey"
      description="Professional emergency roofing services in Weybridge Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Weybridge Surrey"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInWeybridgeSurrey;
