import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInSloughBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Slough Berkshire"
      description="Professional emergency roofing services in Slough Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Slough Berkshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInSloughBerkshire;
