import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInRustingtonWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Rustington West Sussex"
      description="Professional emergency roofing services in Rustington West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Rustington West Sussex"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInRustingtonWestSussex;
