import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInCamberleySurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Camberley Surrey"
      description="Professional emergency roofing services in Camberley Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Camberley Surrey"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInCamberleySurrey;
