import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInWiltonWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Wilton Wiltshire"
      description="Professional emergency roofing services in Wilton Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Wilton Wiltshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInWiltonWiltshire;
