import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInStainesSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Staines Surrey"
      description="Professional emergency roofing services in Staines Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Staines Surrey"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInStainesSurrey;
