import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInNewportPagnellBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Newport Pagnell Buckinghamshire"
      description="Professional emergency roofing services in Newport Pagnell Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Newport Pagnell Buckinghamshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInNewportPagnellBuckinghamshire;
