import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInWoodstockOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Woodstock Oxfordshire"
      description="Professional emergency roofing services in Woodstock Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Woodstock Oxfordshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInWoodstockOxfordshire;
