import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInRoyalWoottonBassettWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Royal Wootton Bassett Wiltshire"
      description="Professional emergency roofing services in Royal Wootton Bassett Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Royal Wootton Bassett Wiltshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInRoyalWoottonBassettWiltshire;
