import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInSwindonWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Swindon Wiltshire"
      description="Professional emergency roofing services in Swindon Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Swindon Wiltshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInSwindonWiltshire;
