import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInGosportHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Gosport Hampshire"
      description="Professional emergency roofing services in Gosport Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Gosport Hampshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInGosportHampshire;
