import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInCirencesterGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Cirencester Gloucestershire"
      description="Professional emergency roofing services in Cirencester Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Cirencester Gloucestershire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInCirencesterGloucestershire;
