import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInBradfordOnAvonWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Bradford On Avon Wiltshire"
      description="Professional emergency roofing services in Bradford On Avon Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Bradford On Avon Wiltshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInBradfordOnAvonWiltshire;
