import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInFairfordGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Fairford Gloucestershire"
      description="Professional emergency roofing services in Fairford Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Fairford Gloucestershire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInFairfordGloucestershire;
