import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInBicesterOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Bicester Oxfordshire"
      description="Professional emergency roofing services in Bicester Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Bicester Oxfordshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInBicesterOxfordshire;
