import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInCheltenhamGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Cheltenham Gloucestershire"
      description="Professional emergency roofing services in Cheltenham Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Cheltenham Gloucestershire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInCheltenhamGloucestershire;
