import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInLittlehamptonWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Littlehampton West Sussex"
      description="Professional emergency roofing services in Littlehampton West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Littlehampton West Sussex"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInLittlehamptonWestSussex;
