import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInMarlowBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Marlow Buckinghamshire"
      description="Professional emergency roofing services in Marlow Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Marlow Buckinghamshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInMarlowBuckinghamshire;
