import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInSummertownOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Summertown Oxfordshire"
      description="Professional emergency roofing services in Summertown Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Summertown Oxfordshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInSummertownOxfordshire;
