import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInEsherSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Esher Surrey"
      description="Professional emergency roofing services in Esher Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Esher Surrey"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInEsherSurrey;
