import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInHenleyOnThamesOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Henley On Thames Oxfordshire"
      description="Professional emergency roofing services in Henley On Thames Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Henley On Thames Oxfordshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInHenleyOnThamesOxfordshire;
