import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInChippingNortonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Chipping Norton Oxfordshire"
      description="Professional emergency roofing services in Chipping Norton Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Chipping Norton Oxfordshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInChippingNortonOxfordshire;
