import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInTrowbridgeWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Trowbridge Wiltshire"
      description="Professional emergency roofing services in Trowbridge Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Trowbridge Wiltshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInTrowbridgeWiltshire;
