import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInDorkingSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Dorking Surrey"
      description="Professional emergency roofing services in Dorking Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Dorking Surrey"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInDorkingSurrey;
