import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInWinchcombeGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Winchcombe Gloucestershire"
      description="Professional emergency roofing services in Winchcombe Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Winchcombe Gloucestershire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInWinchcombeGloucestershire;
