import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInBanburyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Banbury Oxfordshire"
      description="Professional emergency roofing services in Banbury Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Banbury Oxfordshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInBanburyOxfordshire;
