import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInDevizesWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Devizes Wiltshire"
      description="Professional emergency roofing services in Devizes Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Devizes Wiltshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInDevizesWiltshire;
