import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInBansteadSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Banstead Surrey"
      description="Professional emergency roofing services in Banstead Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Banstead Surrey"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInBansteadSurrey;
