import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInPortsmouthHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Portsmouth Hampshire"
      description="Professional emergency roofing services in Portsmouth Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Portsmouth Hampshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInPortsmouthHampshire;
