import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInSalisburyWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Salisbury Wiltshire"
      description="Professional emergency roofing services in Salisbury Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Salisbury Wiltshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInSalisburyWiltshire;
