import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInChippingCampdenGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Chipping Campden Gloucestershire"
      description="Professional emergency roofing services in Chipping Campden Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Chipping Campden Gloucestershire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInChippingCampdenGloucestershire;
