import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInEastGrinsteadWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in East Grinstead West Sussex"
      description="Professional emergency roofing services in East Grinstead West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="East Grinstead West Sussex"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInEastGrinsteadWestSussex;
