import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInCorshamWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Corsham Wiltshire"
      description="Professional emergency roofing services in Corsham Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Corsham Wiltshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInCorshamWiltshire;
