import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInCranleighSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Cranleigh Surrey"
      description="Professional emergency roofing services in Cranleigh Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Cranleigh Surrey"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInCranleighSurrey;
