import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInHeadingtonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Headington Oxfordshire"
      description="Professional emergency roofing services in Headington Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Headington Oxfordshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInHeadingtonOxfordshire;
