import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInMelkshamWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Melksham Wiltshire"
      description="Professional emergency roofing services in Melksham Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Melksham Wiltshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInMelkshamWiltshire;
