import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInLeatherheadSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Leatherhead Surrey"
      description="Professional emergency roofing services in Leatherhead Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Leatherhead Surrey"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInLeatherheadSurrey;
