import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInTetburyGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Tetbury Gloucestershire"
      description="Professional emergency roofing services in Tetbury Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Tetbury Gloucestershire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInTetburyGloucestershire;
