import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInAylesburyBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Aylesbury Buckinghamshire"
      description="Professional emergency roofing services in Aylesbury Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Aylesbury Buckinghamshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInAylesburyBuckinghamshire;
