import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInHenfieldWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Henfield West Sussex"
      description="Professional emergency roofing services in Henfield West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Henfield West Sussex"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInHenfieldWestSussex;
