import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInThameOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Thame Oxfordshire"
      description="Professional emergency roofing services in Thame Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Thame Oxfordshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInThameOxfordshire;
