import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInWokingSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Woking Surrey"
      description="Professional emergency roofing services in Woking Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Woking Surrey"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInWokingSurrey;
