import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInEghamSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Egham Surrey"
      description="Professional emergency roofing services in Egham Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Egham Surrey"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInEghamSurrey;
