import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInFarehamHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Fareham Hampshire"
      description="Professional emergency roofing services in Fareham Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Fareham Hampshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInFarehamHampshire;
