import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInWarminsterWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Warminster Wiltshire"
      description="Professional emergency roofing services in Warminster Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Warminster Wiltshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInWarminsterWiltshire;
