import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInBurgessHillWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Burgess Hill West Sussex"
      description="Professional emergency roofing services in Burgess Hill West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Burgess Hill West Sussex"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInBurgessHillWestSussex;
