import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInPrincesRisboroughBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Princes Risborough Buckinghamshire"
      description="Professional emergency roofing services in Princes Risborough Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Princes Risborough Buckinghamshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInPrincesRisboroughBuckinghamshire;
