import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInNewburyBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Newbury Berkshire"
      description="Professional emergency roofing services in Newbury Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Newbury Berkshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInNewburyBerkshire;
