import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInIffleyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Iffley Oxfordshire"
      description="Professional emergency roofing services in Iffley Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Iffley Oxfordshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInIffleyOxfordshire;
