import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInWantageOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Wantage Oxfordshire"
      description="Professional emergency roofing services in Wantage Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Wantage Oxfordshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInWantageOxfordshire;
