import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInWindsorBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Windsor Berkshire"
      description="Professional emergency roofing services in Windsor Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Windsor Berkshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInWindsorBerkshire;
