import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInCrickladeWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Cricklade Wiltshire"
      description="Professional emergency roofing services in Cricklade Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Cricklade Wiltshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInCrickladeWiltshire;
