import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInWinchesterHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Winchester Hampshire"
      description="Professional emergency roofing services in Winchester Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Winchester Hampshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInWinchesterHampshire;
