import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInRoseHillOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Rose Hill Oxfordshire"
      description="Professional emergency roofing services in Rose Hill Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Rose Hill Oxfordshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInRoseHillOxfordshire;
