import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInRedhillSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Redhill Surrey"
      description="Professional emergency roofing services in Redhill Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Redhill Surrey"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInRedhillSurrey;
