import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInHorshamWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Horsham West Sussex"
      description="Professional emergency roofing services in Horsham West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Horsham West Sussex"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInHorshamWestSussex;
