import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInPetersfieldHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Petersfield Hampshire"
      description="Professional emergency roofing services in Petersfield Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Petersfield Hampshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInPetersfieldHampshire;
