import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInBotleyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Botley Oxfordshire"
      description="Professional emergency roofing services in Botley Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Botley Oxfordshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInBotleyOxfordshire;
