import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInNewentGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Newent Gloucestershire"
      description="Professional emergency roofing services in Newent Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Newent Gloucestershire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInNewentGloucestershire;
