import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInWatlingtonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Watlington Oxfordshire"
      description="Professional emergency roofing services in Watlington Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Watlington Oxfordshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInWatlingtonOxfordshire;
