import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInStroudGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Stroud Gloucestershire"
      description="Professional emergency roofing services in Stroud Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Stroud Gloucestershire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInStroudGloucestershire;
