import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInMidhurstWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Midhurst West Sussex"
      description="Professional emergency roofing services in Midhurst West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Midhurst West Sussex"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInMidhurstWestSussex;
