import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInChippenhamWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Chippenham Wiltshire"
      description="Professional emergency roofing services in Chippenham Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Chippenham Wiltshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInChippenhamWiltshire;
