import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInOlneyBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Olney Buckinghamshire"
      description="Professional emergency roofing services in Olney Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Olney Buckinghamshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInOlneyBuckinghamshire;
