import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInMiltonKeynesBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Milton Keynes Buckinghamshire"
      description="Professional emergency roofing services in Milton Keynes Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Milton Keynes Buckinghamshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInMiltonKeynesBuckinghamshire;
