import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInBuckinghamBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Buckingham Buckinghamshire"
      description="Professional emergency roofing services in Buckingham Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Buckingham Buckinghamshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInBuckinghamBuckinghamshire;
