import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInLechladeGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Lechlade Gloucestershire"
      description="Professional emergency roofing services in Lechlade Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Lechlade Gloucestershire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInLechladeGloucestershire;
