import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInStonyStratfordBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Stony Stratford Buckinghamshire"
      description="Professional emergency roofing services in Stony Stratford Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Stony Stratford Buckinghamshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInStonyStratfordBuckinghamshire;
