import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInBeaconsfieldBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Beaconsfield Buckinghamshire"
      description="Professional emergency roofing services in Beaconsfield Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Beaconsfield Buckinghamshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInBeaconsfieldBuckinghamshire;
