import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInShorehamBySeaWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Shoreham By Sea West Sussex"
      description="Professional emergency roofing services in Shoreham By Sea West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Shoreham By Sea West Sussex"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInShorehamBySeaWestSussex;
