import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInFaringdonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Faringdon Oxfordshire"
      description="Professional emergency roofing services in Faringdon Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Faringdon Oxfordshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInFaringdonOxfordshire;
