import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInReigateSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Reigate Surrey"
      description="Professional emergency roofing services in Reigate Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Reigate Surrey"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInReigateSurrey;
