import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInBognorRegisWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Bognor Regis West Sussex"
      description="Professional emergency roofing services in Bognor Regis West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Bognor Regis West Sussex"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInBognorRegisWestSussex;
