import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInEynshamOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Eynsham Oxfordshire"
      description="Professional emergency roofing services in Eynsham Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Eynsham Oxfordshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInEynshamOxfordshire;
