import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInHavantHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Havant Hampshire"
      description="Professional emergency roofing services in Havant Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Havant Hampshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInHavantHampshire;
