import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const EmergencyRoofingInBracknellBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Emergency Roofing in Bracknell Berkshire"
      description="Professional emergency roofing services in Bracknell Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Bracknell Berkshire"
      service="Emergency Roofing"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default EmergencyRoofingInBracknellBerkshire;
