import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInStainesSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Staines Surrey"
      description="Professional gutter services services in Staines Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Staines Surrey"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInStainesSurrey;
