import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInAmershamBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Amersham Buckinghamshire"
      description="Professional gutter services services in Amersham Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Amersham Buckinghamshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInAmershamBuckinghamshire;
