import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInWottonUnderEdgeGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Wotton Under Edge Gloucestershire"
      description="Professional gutter services services in Wotton Under Edge Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Wotton Under Edge Gloucestershire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInWottonUnderEdgeGloucestershire;
