import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInCranleighSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Cranleigh Surrey"
      description="Professional gutter services services in Cranleigh Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Cranleigh Surrey"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInCranleighSurrey;
