import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInBuckinghamBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Buckingham Buckinghamshire"
      description="Professional gutter services services in Buckingham Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Buckingham Buckinghamshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInBuckinghamBuckinghamshire;
