import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInAbingdonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Abingdon Oxfordshire"
      description="Professional gutter services services in Abingdon Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Abingdon Oxfordshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInAbingdonOxfordshire;
