import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInRoyalWoottonBassettWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Royal Wootton Bassett Wiltshire"
      description="Professional gutter services services in Royal Wootton Bassett Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Royal Wootton Bassett Wiltshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInRoyalWoottonBassettWiltshire;
