import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInRingwoodHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Ringwood Hampshire"
      description="Professional gutter services services in Ringwood Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Ringwood Hampshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInRingwoodHampshire;
