import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInOlneyBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Olney Buckinghamshire"
      description="Professional gutter services services in Olney Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Olney Buckinghamshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInOlneyBuckinghamshire;
