import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInWitneyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Witney Oxfordshire"
      description="Professional gutter services services in Witney Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Witney Oxfordshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInWitneyOxfordshire;
