import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInDursleyGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Dursley Gloucestershire"
      description="Professional gutter services services in Dursley Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Dursley Gloucestershire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInDursleyGloucestershire;
