import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInMaidenheadBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Maidenhead Berkshire"
      description="Professional gutter services services in Maidenhead Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Maidenhead Berkshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInMaidenheadBerkshire;
