import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInWestburyWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Westbury Wiltshire"
      description="Professional gutter services services in Westbury Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Westbury Wiltshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInWestburyWiltshire;
