import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInChichesterWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Chichester West Sussex"
      description="Professional gutter services services in Chichester West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Chichester West Sussex"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInChichesterWestSussex;
