import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInThameOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Thame Oxfordshire"
      description="Professional gutter services services in Thame Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Thame Oxfordshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInThameOxfordshire;
