import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInMidhurstWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Midhurst West Sussex"
      description="Professional gutter services services in Midhurst West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Midhurst West Sussex"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInMidhurstWestSussex;
