import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInWindsorBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Windsor Berkshire"
      description="Professional gutter services services in Windsor Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Windsor Berkshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInWindsorBerkshire;
