import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInSteyningWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Steyning West Sussex"
      description="Professional gutter services services in Steyning West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Steyning West Sussex"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInSteyningWestSussex;
