import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInHorshamWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Horsham West Sussex"
      description="Professional gutter services services in Horsham West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Horsham West Sussex"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInHorshamWestSussex;
