import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInCheshamBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Chesham Buckinghamshire"
      description="Professional gutter services services in Chesham Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Chesham Buckinghamshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInCheshamBuckinghamshire;
