import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInHavantHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Havant Hampshire"
      description="Professional gutter services services in Havant Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Havant Hampshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInHavantHampshire;
