import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInHenfieldWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Henfield West Sussex"
      description="Professional gutter services services in Henfield West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Henfield West Sussex"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInHenfieldWestSussex;
