import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInBracknellBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Bracknell Berkshire"
      description="Professional gutter services services in Bracknell Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Bracknell Berkshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInBracknellBerkshire;
