import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInArundelWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Arundel West Sussex"
      description="Professional gutter services services in Arundel West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Arundel West Sussex"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInArundelWestSussex;
