import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInMelkshamWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Melksham Wiltshire"
      description="Professional gutter services services in Melksham Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Melksham Wiltshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInMelkshamWiltshire;
