import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInWarminsterWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Warminster Wiltshire"
      description="Professional gutter services services in Warminster Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Warminster Wiltshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInWarminsterWiltshire;
