import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInTetburyGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Tetbury Gloucestershire"
      description="Professional gutter services services in Tetbury Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Tetbury Gloucestershire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInTetburyGloucestershire;
