import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInPetersfieldHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Petersfield Hampshire"
      description="Professional gutter services services in Petersfield Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Petersfield Hampshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInPetersfieldHampshire;
