import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInChippingNortonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Chipping Norton Oxfordshire"
      description="Professional gutter services services in Chipping Norton Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Chipping Norton Oxfordshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInChippingNortonOxfordshire;
