import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInEsherSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Esher Surrey"
      description="Professional gutter services services in Esher Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Esher Surrey"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInEsherSurrey;
