import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInStroudGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Stroud Gloucestershire"
      description="Professional gutter services services in Stroud Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Stroud Gloucestershire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInStroudGloucestershire;
