import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInGerrardsCrossBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Gerrards Cross Buckinghamshire"
      description="Professional gutter services services in Gerrards Cross Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Gerrards Cross Buckinghamshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInGerrardsCrossBuckinghamshire;
