import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInRedhillSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Redhill Surrey"
      description="Professional gutter services services in Redhill Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Redhill Surrey"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInRedhillSurrey;
