import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInCamberleySurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Camberley Surrey"
      description="Professional gutter services services in Camberley Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Camberley Surrey"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInCamberleySurrey;
