import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInWendoverBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Wendover Buckinghamshire"
      description="Professional gutter services services in Wendover Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Wendover Buckinghamshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInWendoverBuckinghamshire;
