import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInNewburyBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Newbury Berkshire"
      description="Professional gutter services services in Newbury Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Newbury Berkshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInNewburyBerkshire;
