import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInChippenhamWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Chippenham Wiltshire"
      description="Professional gutter services services in Chippenham Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Chippenham Wiltshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInChippenhamWiltshire;
