import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInCrawleyWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Crawley West Sussex"
      description="Professional gutter services services in Crawley West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Crawley West Sussex"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInCrawleyWestSussex;
