import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInCowleyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Cowley Oxfordshire"
      description="Professional gutter services services in Cowley Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Cowley Oxfordshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInCowleyOxfordshire;
