import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInSwindonWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Swindon Wiltshire"
      description="Professional gutter services services in Swindon Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Swindon Wiltshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInSwindonWiltshire;
