import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInGuildfordSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Guildford Surrey"
      description="Professional gutter services services in Guildford Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Guildford Surrey"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInGuildfordSurrey;
