import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInChalfontStPeterBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Chalfont St Peter Buckinghamshire"
      description="Professional gutter services services in Chalfont St Peter Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Chalfont St Peter Buckinghamshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInChalfontStPeterBuckinghamshire;
