import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInShorehamBySeaWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Shoreham By Sea West Sussex"
      description="Professional gutter services services in Shoreham By Sea West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Shoreham By Sea West Sussex"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInShorehamBySeaWestSussex;
