import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInDidcotOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Didcot Oxfordshire"
      description="Professional gutter services services in Didcot Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Didcot Oxfordshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInDidcotOxfordshire;
