import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInWantageOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Wantage Oxfordshire"
      description="Professional gutter services services in Wantage Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Wantage Oxfordshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInWantageOxfordshire;
