import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInEpsomSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Epsom Surrey"
      description="Professional gutter services services in Epsom Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Epsom Surrey"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInEpsomSurrey;
