import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInBognorRegisWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Bognor Regis West Sussex"
      description="Professional gutter services services in Bognor Regis West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Bognor Regis West Sussex"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInBognorRegisWestSussex;
