import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInTottonHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Totton Hampshire"
      description="Professional gutter services services in Totton Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Totton Hampshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInTottonHampshire;
