import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInCrickladeWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Cricklade Wiltshire"
      description="Professional gutter services services in Cricklade Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Cricklade Wiltshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInCrickladeWiltshire;
