import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInGloucesterGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Gloucester Gloucestershire"
      description="Professional gutter services services in Gloucester Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Gloucester Gloucestershire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInGloucesterGloucestershire;
