import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInHorleySurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Horley Surrey"
      description="Professional gutter services services in Horley Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Horley Surrey"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInHorleySurrey;
