import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInHaywardsHeathWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Haywards Heath West Sussex"
      description="Professional gutter services services in Haywards Heath West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Haywards Heath West Sussex"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInHaywardsHeathWestSussex;
