import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInNailsworthGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Nailsworth Gloucestershire"
      description="Professional gutter services services in Nailsworth Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Nailsworth Gloucestershire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInNailsworthGloucestershire;
