import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInMarlowBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Marlow Buckinghamshire"
      description="Professional gutter services services in Marlow Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Marlow Buckinghamshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInMarlowBuckinghamshire;
