import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInFarehamHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Fareham Hampshire"
      description="Professional gutter services services in Fareham Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Fareham Hampshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInFarehamHampshire;
