import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInAylesburyBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Aylesbury Buckinghamshire"
      description="Professional gutter services services in Aylesbury Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Aylesbury Buckinghamshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInAylesburyBuckinghamshire;
