import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInSummertownOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Summertown Oxfordshire"
      description="Professional gutter services services in Summertown Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Summertown Oxfordshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInSummertownOxfordshire;
