import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInPetworthWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Petworth West Sussex"
      description="Professional gutter services services in Petworth West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Petworth West Sussex"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInPetworthWestSussex;
