import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInWinchcombeGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Winchcombe Gloucestershire"
      description="Professional gutter services services in Winchcombe Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Winchcombe Gloucestershire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInWinchcombeGloucestershire;
