import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInWinslowBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Winslow Buckinghamshire"
      description="Professional gutter services services in Winslow Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Winslow Buckinghamshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInWinslowBuckinghamshire;
