import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInSouthwickWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Southwick West Sussex"
      description="Professional gutter services services in Southwick West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Southwick West Sussex"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInSouthwickWestSussex;
