import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInWokingSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Woking Surrey"
      description="Professional gutter services services in Woking Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Woking Surrey"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInWokingSurrey;
