import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInStonehouseGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Stonehouse Gloucestershire"
      description="Professional gutter services services in Stonehouse Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Stonehouse Gloucestershire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInStonehouseGloucestershire;
