import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInWokinghamBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Wokingham Berkshire"
      description="Professional gutter services services in Wokingham Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Wokingham Berkshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInWokinghamBerkshire;
