import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInOxfordOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Oxford Oxfordshire"
      description="Professional gutter services services in Oxford Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Oxford Oxfordshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInOxfordOxfordshire;
