import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInBradfordOnAvonWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Bradford On Avon Wiltshire"
      description="Professional gutter services services in Bradford On Avon Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Bradford On Avon Wiltshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInBradfordOnAvonWiltshire;
