import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInMalmesburyWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Malmesbury Wiltshire"
      description="Professional gutter services services in Malmesbury Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Malmesbury Wiltshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInMalmesburyWiltshire;
