import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInFaringdonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Faringdon Oxfordshire"
      description="Professional gutter services services in Faringdon Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Faringdon Oxfordshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInFaringdonOxfordshire;
