import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInDevizesWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Devizes Wiltshire"
      description="Professional gutter services services in Devizes Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Devizes Wiltshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInDevizesWiltshire;
