import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInWoodstockOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Woodstock Oxfordshire"
      description="Professional gutter services services in Woodstock Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Woodstock Oxfordshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInWoodstockOxfordshire;
