import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInDorkingSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Dorking Surrey"
      description="Professional gutter services services in Dorking Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Dorking Surrey"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInDorkingSurrey;
