import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInPewseyWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Pewsey Wiltshire"
      description="Professional gutter services services in Pewsey Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Pewsey Wiltshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInPewseyWiltshire;
