import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInBansteadSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Banstead Surrey"
      description="Professional gutter services services in Banstead Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Banstead Surrey"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInBansteadSurrey;
