import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInCheltenhamGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Cheltenham Gloucestershire"
      description="Professional gutter services services in Cheltenham Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Cheltenham Gloucestershire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInCheltenhamGloucestershire;
