import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInEastGrinsteadWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in East Grinstead West Sussex"
      description="Professional gutter services services in East Grinstead West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="East Grinstead West Sussex"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInEastGrinsteadWestSussex;
