import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInSelseyWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Selsey West Sussex"
      description="Professional gutter services services in Selsey West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Selsey West Sussex"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInSelseyWestSussex;
