import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInReadingBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Reading Berkshire"
      description="Professional gutter services services in Reading Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Reading Berkshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInReadingBerkshire;
