import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInCharlburyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Charlbury Oxfordshire"
      description="Professional gutter services services in Charlbury Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Charlbury Oxfordshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInCharlburyOxfordshire;
