import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInHighWycombeBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in High Wycombe Buckinghamshire"
      description="Professional gutter services services in High Wycombe Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="High Wycombe Buckinghamshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInHighWycombeBuckinghamshire;
