import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInMarstonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Marston Oxfordshire"
      description="Professional gutter services services in Marston Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Marston Oxfordshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInMarstonOxfordshire;
