import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInWolvercoteOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Wolvercote Oxfordshire"
      description="Professional gutter services services in Wolvercote Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Wolvercote Oxfordshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInWolvercoteOxfordshire;
