import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInFarnboroughHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Farnborough Hampshire"
      description="Professional gutter services services in Farnborough Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Farnborough Hampshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInFarnboroughHampshire;
