import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInBlackbirdLeysOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Blackbird Leys Oxfordshire"
      description="Professional gutter services services in Blackbird Leys Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Blackbird Leys Oxfordshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInBlackbirdLeysOxfordshire;
