import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInAldershotHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Aldershot Hampshire"
      description="Professional gutter services services in Aldershot Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Aldershot Hampshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInAldershotHampshire;
