import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInMiltonKeynesBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Milton Keynes Buckinghamshire"
      description="Professional gutter services services in Milton Keynes Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Milton Keynes Buckinghamshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInMiltonKeynesBuckinghamshire;
