import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInGreatMissendenBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Great Missenden Buckinghamshire"
      description="Professional gutter services services in Great Missenden Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Great Missenden Buckinghamshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInGreatMissendenBuckinghamshire;
