import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInWallingfordOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Wallingford Oxfordshire"
      description="Professional gutter services services in Wallingford Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Wallingford Oxfordshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInWallingfordOxfordshire;
