import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInChippingCampdenGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Chipping Campden Gloucestershire"
      description="Professional gutter services services in Chipping Campden Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Chipping Campden Gloucestershire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInChippingCampdenGloucestershire;
