import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInHaslemereSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Haslemere Surrey"
      description="Professional gutter services services in Haslemere Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Haslemere Surrey"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInHaslemereSurrey;
