import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInBurnhamBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Burnham Buckinghamshire"
      description="Professional gutter services services in Burnham Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Burnham Buckinghamshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInBurnhamBuckinghamshire;
