import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInPrincesRisboroughBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Princes Risborough Buckinghamshire"
      description="Professional gutter services services in Princes Risborough Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Princes Risborough Buckinghamshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInPrincesRisboroughBuckinghamshire;
