import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInBanburyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Banbury Oxfordshire"
      description="Professional gutter services services in Banbury Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Banbury Oxfordshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInBanburyOxfordshire;
