import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInAltonHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Alton Hampshire"
      description="Professional gutter services services in Alton Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Alton Hampshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInAltonHampshire;
