import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInJerichoOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Jericho Oxfordshire"
      description="Professional gutter services services in Jericho Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Jericho Oxfordshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInJerichoOxfordshire;
