import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInEastleighHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Eastleigh Hampshire"
      description="Professional gutter services services in Eastleigh Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Eastleigh Hampshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInEastleighHampshire;
