import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInAmesburyWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Amesbury Wiltshire"
      description="Professional gutter services services in Amesbury Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Amesbury Wiltshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInAmesburyWiltshire;
