import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInSloughBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Slough Berkshire"
      description="Professional gutter services services in Slough Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Slough Berkshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInSloughBerkshire;
