import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInCartertonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Carterton Oxfordshire"
      description="Professional gutter services services in Carterton Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Carterton Oxfordshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInCartertonOxfordshire;
