import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInFleetHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Fleet Hampshire"
      description="Professional gutter services services in Fleet Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Fleet Hampshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInFleetHampshire;
