import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInMarlboroughWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Marlborough Wiltshire"
      description="Professional gutter services services in Marlborough Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Marlborough Wiltshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInMarlboroughWiltshire;
