import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInEghamSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Egham Surrey"
      description="Professional gutter services services in Egham Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Egham Surrey"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInEghamSurrey;
