import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInBeaconsfieldBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Beaconsfield Buckinghamshire"
      description="Professional gutter services services in Beaconsfield Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Beaconsfield Buckinghamshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInBeaconsfieldBuckinghamshire;
