import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInNewentGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Newent Gloucestershire"
      description="Professional gutter services services in Newent Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Newent Gloucestershire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInNewentGloucestershire;
