import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInFairfordGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Fairford Gloucestershire"
      description="Professional gutter services services in Fairford Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Fairford Gloucestershire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInFairfordGloucestershire;
