import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInReigateSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Reigate Surrey"
      description="Professional gutter services services in Reigate Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Reigate Surrey"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInReigateSurrey;
