import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInEynshamOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Eynsham Oxfordshire"
      description="Professional gutter services services in Eynsham Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Eynsham Oxfordshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInEynshamOxfordshire;
