import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInBotleyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Botley Oxfordshire"
      description="Professional gutter services services in Botley Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Botley Oxfordshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInBotleyOxfordshire;
