import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInStonyStratfordBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Stony Stratford Buckinghamshire"
      description="Professional gutter services services in Stony Stratford Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Stony Stratford Buckinghamshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInStonyStratfordBuckinghamshire;
