import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInWeybridgeSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Weybridge Surrey"
      description="Professional gutter services services in Weybridge Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Weybridge Surrey"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInWeybridgeSurrey;
