import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInBerkeleyGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Berkeley Gloucestershire"
      description="Professional gutter services services in Berkeley Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Berkeley Gloucestershire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInBerkeleyGloucestershire;
