import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInRustingtonWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Rustington West Sussex"
      description="Professional gutter services services in Rustington West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Rustington West Sussex"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInRustingtonWestSussex;
