import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInFarnhamSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Farnham Surrey"
      description="Professional gutter services services in Farnham Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Farnham Surrey"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInFarnhamSurrey;
