import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInGodalmingSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Godalming Surrey"
      description="Professional gutter services services in Godalming Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Godalming Surrey"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInGodalmingSurrey;
