import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInSouthamptonHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Southampton Hampshire"
      description="Professional gutter services services in Southampton Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Southampton Hampshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInSouthamptonHampshire;
