import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInCalneWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Calne Wiltshire"
      description="Professional gutter services services in Calne Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Calne Wiltshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInCalneWiltshire;
