import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInLeatherheadSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Leatherhead Surrey"
      description="Professional gutter services services in Leatherhead Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Leatherhead Surrey"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInLeatherheadSurrey;
