import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInTidworthWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Tidworth Wiltshire"
      description="Professional gutter services services in Tidworth Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Tidworth Wiltshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInTidworthWiltshire;
