import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInTrowbridgeWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Trowbridge Wiltshire"
      description="Professional gutter services services in Trowbridge Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Trowbridge Wiltshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInTrowbridgeWiltshire;
