import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const GutterServicesInWatlingtonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Gutter Services in Watlington Oxfordshire"
      description="Professional gutter services services in Watlington Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Watlington Oxfordshire"
      service="Gutter Services"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default GutterServicesInWatlingtonOxfordshire;
