import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInGloucesterGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Gloucester Gloucestershire"
      description="Professional roof installation services in Gloucester Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Gloucester Gloucestershire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInGloucesterGloucestershire;
