import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInAldershotHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Aldershot Hampshire"
      description="Professional roof maintenance services in Aldershot Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Aldershot Hampshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInAldershotHampshire;
