import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInTetburyGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Tetbury Gloucestershire"
      description="Professional roof inspection services in Tetbury Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Tetbury Gloucestershire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInTetburyGloucestershire;
