import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInEastGrinsteadWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in East Grinstead West Sussex"
      description="Professional roof installation services in East Grinstead West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="East Grinstead West Sussex"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInEastGrinsteadWestSussex;
