import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInSummertownOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Summertown Oxfordshire"
      description="Professional roof inspection services in Summertown Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Summertown Oxfordshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInSummertownOxfordshire;
