import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInAbingdonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Abingdon Oxfordshire"
      description="Professional roof maintenance services in Abingdon Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Abingdon Oxfordshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInAbingdonOxfordshire;
