import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInGuildfordSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Guildford Surrey"
      description="Professional roof maintenance services in Guildford Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Guildford Surrey"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInGuildfordSurrey;
