import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInRoyalWoottonBassettWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Royal Wootton Bassett Wiltshire"
      description="Professional roof installation services in Royal Wootton Bassett Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Royal Wootton Bassett Wiltshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInRoyalWoottonBassettWiltshire;
