import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInRingwoodHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Ringwood Hampshire"
      description="Professional roof maintenance services in Ringwood Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Ringwood Hampshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInRingwoodHampshire;
