import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInWestburyWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Westbury Wiltshire"
      description="Professional roof inspection services in Westbury Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Westbury Wiltshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInWestburyWiltshire;
