import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInBradfordOnAvonWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Bradford On Avon Wiltshire"
      description="Professional roof installation services in Bradford On Avon Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Bradford On Avon Wiltshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInBradfordOnAvonWiltshire;
