import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInHenleyOnThamesOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Henley On Thames Oxfordshire"
      description="Professional roof maintenance services in Henley On Thames Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Henley On Thames Oxfordshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInHenleyOnThamesOxfordshire;
