import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInBuckinghamBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Buckingham Buckinghamshire"
      description="Professional roof installation services in Buckingham Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Buckingham Buckinghamshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInBuckinghamBuckinghamshire;
