import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInBansteadSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Banstead Surrey"
      description="Professional roof inspection services in Banstead Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Banstead Surrey"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInBansteadSurrey;
