import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInRoyalWoottonBassettWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Royal Wootton Bassett Wiltshire"
      description="Professional roof maintenance services in Royal Wootton Bassett Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Royal Wootton Bassett Wiltshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInRoyalWoottonBassettWiltshire;
