import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInLechladeGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Lechlade Gloucestershire"
      description="Professional roof installation services in Lechlade Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Lechlade Gloucestershire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInLechladeGloucestershire;
