import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInOxfordOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Oxford Oxfordshire"
      description="Professional roof installation services in Oxford Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Oxford Oxfordshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInOxfordOxfordshire;
