import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInMelkshamWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Melksham Wiltshire"
      description="Professional roof inspection services in Melksham Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Melksham Wiltshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInMelkshamWiltshire;
