import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInGreatMissendenBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Great Missenden Buckinghamshire"
      description="Professional roof installation services in Great Missenden Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Great Missenden Buckinghamshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInGreatMissendenBuckinghamshire;
