import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInHaslemereSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Haslemere Surrey"
      description="Professional roof installation services in Haslemere Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Haslemere Surrey"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInHaslemereSurrey;
