import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInFairfordGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Fairford Gloucestershire"
      description="Professional roof installation services in Fairford Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Fairford Gloucestershire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInFairfordGloucestershire;
