import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInDevizesWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Devizes Wiltshire"
      description="Professional roof maintenance services in Devizes Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Devizes Wiltshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInDevizesWiltshire;
