import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInGosportHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Gosport Hampshire"
      description="Professional roof maintenance services in Gosport Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Gosport Hampshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInGosportHampshire;
