import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInHavantHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Havant Hampshire"
      description="Professional roof installation services in Havant Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Havant Hampshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInHavantHampshire;
