import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInEynshamOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Eynsham Oxfordshire"
      description="Professional roof installation services in Eynsham Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Eynsham Oxfordshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInEynshamOxfordshire;
