import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInArundelWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Arundel West Sussex"
      description="Professional roof maintenance services in Arundel West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Arundel West Sussex"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInArundelWestSussex;
