import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInSummertownOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Summertown Oxfordshire"
      description="Professional roof installation services in Summertown Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Summertown Oxfordshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInSummertownOxfordshire;
