import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInFleetHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Fleet Hampshire"
      description="Professional roof installation services in Fleet Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Fleet Hampshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInFleetHampshire;
