import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInCrawleyWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Crawley West Sussex"
      description="Professional roof maintenance services in Crawley West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Crawley West Sussex"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInCrawleyWestSussex;
