import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInLymingtonHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Lymington Hampshire"
      description="Professional roof maintenance services in Lymington Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Lymington Hampshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInLymingtonHampshire;
