import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInMidhurstWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Midhurst West Sussex"
      description="Professional roof maintenance services in Midhurst West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Midhurst West Sussex"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInMidhurstWestSussex;
