import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInEpsomSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Epsom Surrey"
      description="Professional roof installation services in Epsom Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Epsom Surrey"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInEpsomSurrey;
