import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInWokingSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Woking Surrey"
      description="Professional roof maintenance services in Woking Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Woking Surrey"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInWokingSurrey;
