import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInBanburyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Banbury Oxfordshire"
      description="Professional roof installation services in Banbury Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Banbury Oxfordshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInBanburyOxfordshire;
