import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInWokinghamBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Wokingham Berkshire"
      description="Professional roof inspection services in Wokingham Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Wokingham Berkshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInWokinghamBerkshire;
