import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInBotleyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Botley Oxfordshire"
      description="Professional roof maintenance services in Botley Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Botley Oxfordshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInBotleyOxfordshire;
