import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInFaringdonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Faringdon Oxfordshire"
      description="Professional roof installation services in Faringdon Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Faringdon Oxfordshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInFaringdonOxfordshire;
