import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInSummertownOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Summertown Oxfordshire"
      description="Professional roof maintenance services in Summertown Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Summertown Oxfordshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInSummertownOxfordshire;
