import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInWokingSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Woking Surrey"
      description="Professional roof installation services in Woking Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Woking Surrey"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInWokingSurrey;
