import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInRustingtonWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Rustington West Sussex"
      description="Professional roof installation services in Rustington West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Rustington West Sussex"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInRustingtonWestSussex;
