import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInBanburyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Banbury Oxfordshire"
      description="Professional roof inspection services in Banbury Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Banbury Oxfordshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInBanburyOxfordshire;
