import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInShorehamBySeaWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Shoreham By Sea West Sussex"
      description="Professional roof inspection services in Shoreham By Sea West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Shoreham By Sea West Sussex"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInShorehamBySeaWestSussex;
