import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInSouthwickWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Southwick West Sussex"
      description="Professional roof maintenance services in Southwick West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Southwick West Sussex"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInSouthwickWestSussex;
