import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInHenleyOnThamesOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Henley On Thames Oxfordshire"
      description="Professional roof inspection services in Henley On Thames Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Henley On Thames Oxfordshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInHenleyOnThamesOxfordshire;
