import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInEsherSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Esher Surrey"
      description="Professional roof installation services in Esher Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Esher Surrey"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInEsherSurrey;
