import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInEpsomSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Epsom Surrey"
      description="Professional roof inspection services in Epsom Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Epsom Surrey"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInEpsomSurrey;
