import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInOxfordOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Oxford Oxfordshire"
      description="Professional roof maintenance services in Oxford Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Oxford Oxfordshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInOxfordOxfordshire;
