import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInFarnhamSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Farnham Surrey"
      description="Professional roof inspection services in Farnham Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Farnham Surrey"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInFarnhamSurrey;
