import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInStonehouseGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Stonehouse Gloucestershire"
      description="Professional roof maintenance services in Stonehouse Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Stonehouse Gloucestershire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInStonehouseGloucestershire;
