import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInBurgessHillWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Burgess Hill West Sussex"
      description="Professional roof installation services in Burgess Hill West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Burgess Hill West Sussex"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInBurgessHillWestSussex;
