import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInWitneyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Witney Oxfordshire"
      description="Professional roof inspection services in Witney Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Witney Oxfordshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInWitneyOxfordshire;
