import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInHorshamWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Horsham West Sussex"
      description="Professional roof maintenance services in Horsham West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Horsham West Sussex"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInHorshamWestSussex;
