import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInStonehouseGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Stonehouse Gloucestershire"
      description="Professional roof inspection services in Stonehouse Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Stonehouse Gloucestershire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInStonehouseGloucestershire;
