import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInHighWycombeBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in High Wycombe Buckinghamshire"
      description="Professional roof maintenance services in High Wycombe Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="High Wycombe Buckinghamshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInHighWycombeBuckinghamshire;
