import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInNewburyBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Newbury Berkshire"
      description="Professional roof inspection services in Newbury Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Newbury Berkshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInNewburyBerkshire;
