import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInWeybridgeSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Weybridge Surrey"
      description="Professional roof inspection services in Weybridge Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Weybridge Surrey"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInWeybridgeSurrey;
