import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInStroudGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Stroud Gloucestershire"
      description="Professional roof inspection services in Stroud Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Stroud Gloucestershire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInStroudGloucestershire;
