import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInWallingfordOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Wallingford Oxfordshire"
      description="Professional roof maintenance services in Wallingford Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Wallingford Oxfordshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInWallingfordOxfordshire;
