import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInMalmesburyWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Malmesbury Wiltshire"
      description="Professional roof maintenance services in Malmesbury Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Malmesbury Wiltshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInMalmesburyWiltshire;
