import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInWitneyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Witney Oxfordshire"
      description="Professional roof maintenance services in Witney Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Witney Oxfordshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInWitneyOxfordshire;
