import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInArundelWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Arundel West Sussex"
      description="Professional roof inspection services in Arundel West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Arundel West Sussex"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInArundelWestSussex;
