import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInBerkeleyGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Berkeley Gloucestershire"
      description="Professional roof maintenance services in Berkeley Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Berkeley Gloucestershire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInBerkeleyGloucestershire;
