import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInGosportHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Gosport Hampshire"
      description="Professional roof installation services in Gosport Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Gosport Hampshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInGosportHampshire;
