import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInMalmesburyWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Malmesbury Wiltshire"
      description="Professional roof installation services in Malmesbury Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Malmesbury Wiltshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInMalmesburyWiltshire;
