import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInHenfieldWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Henfield West Sussex"
      description="Professional roof maintenance services in Henfield West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Henfield West Sussex"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInHenfieldWestSussex;
