import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInHeadingtonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Headington Oxfordshire"
      description="Professional roof maintenance services in Headington Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Headington Oxfordshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInHeadingtonOxfordshire;
