import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInRedhillSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Redhill Surrey"
      description="Professional roof maintenance services in Redhill Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Redhill Surrey"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInRedhillSurrey;
