import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInChippingCampdenGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Chipping Campden Gloucestershire"
      description="Professional roof installation services in Chipping Campden Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Chipping Campden Gloucestershire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInChippingCampdenGloucestershire;
