import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInPewseyWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Pewsey Wiltshire"
      description="Professional roof maintenance services in Pewsey Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Pewsey Wiltshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInPewseyWiltshire;
