import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInWinchcombeGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Winchcombe Gloucestershire"
      description="Professional roof installation services in Winchcombe Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Winchcombe Gloucestershire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInWinchcombeGloucestershire;
