import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInRustingtonWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Rustington West Sussex"
      description="Professional roof maintenance services in Rustington West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Rustington West Sussex"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInRustingtonWestSussex;
