import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInStainesSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Staines Surrey"
      description="Professional roof installation services in Staines Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Staines Surrey"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInStainesSurrey;
