import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInPrincesRisboroughBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Princes Risborough Buckinghamshire"
      description="Professional roof inspection services in Princes Risborough Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Princes Risborough Buckinghamshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInPrincesRisboroughBuckinghamshire;
