import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInCheltenhamGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Cheltenham Gloucestershire"
      description="Professional roof inspection services in Cheltenham Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Cheltenham Gloucestershire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInCheltenhamGloucestershire;
