import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInFarehamHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Fareham Hampshire"
      description="Professional roof maintenance services in Fareham Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Fareham Hampshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInFarehamHampshire;
