import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInAmershamBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Amersham Buckinghamshire"
      description="Professional roof inspection services in Amersham Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Amersham Buckinghamshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInAmershamBuckinghamshire;
