import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInAmershamBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Amersham Buckinghamshire"
      description="Professional roof installation services in Amersham Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Amersham Buckinghamshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInAmershamBuckinghamshire;
