import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInChippenhamWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Chippenham Wiltshire"
      description="Professional roof inspection services in Chippenham Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Chippenham Wiltshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInChippenhamWiltshire;
