import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInWindsorBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Windsor Berkshire"
      description="Professional roof installation services in Windsor Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Windsor Berkshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInWindsorBerkshire;
