import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInHaslemereSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Haslemere Surrey"
      description="Professional roof inspection services in Haslemere Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Haslemere Surrey"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInHaslemereSurrey;
