import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInWindsorBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Windsor Berkshire"
      description="Professional roof maintenance services in Windsor Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Windsor Berkshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInWindsorBerkshire;
