import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInPetworthWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Petworth West Sussex"
      description="Professional roof maintenance services in Petworth West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Petworth West Sussex"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInPetworthWestSussex;
