import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInWorthingWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Worthing West Sussex"
      description="Professional roof installation services in Worthing West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Worthing West Sussex"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInWorthingWestSussex;
