import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInTetburyGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Tetbury Gloucestershire"
      description="Professional roof installation services in Tetbury Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Tetbury Gloucestershire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInTetburyGloucestershire;
