import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInStowOnTheWoldGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Stow On The Wold Gloucestershire"
      description="Professional roof inspection services in Stow On The Wold Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Stow On The Wold Gloucestershire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInStowOnTheWoldGloucestershire;
