import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInArundelWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Arundel West Sussex"
      description="Professional roof installation services in Arundel West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Arundel West Sussex"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInArundelWestSussex;
