import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInDidcotOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Didcot Oxfordshire"
      description="Professional roof inspection services in Didcot Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Didcot Oxfordshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInDidcotOxfordshire;
