import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInGuildfordSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Guildford Surrey"
      description="Professional roof installation services in Guildford Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Guildford Surrey"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInGuildfordSurrey;
