import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInThameOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Thame Oxfordshire"
      description="Professional roof maintenance services in Thame Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Thame Oxfordshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInThameOxfordshire;
