import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInGosportHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Gosport Hampshire"
      description="Professional roof inspection services in Gosport Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Gosport Hampshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInGosportHampshire;
