import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInBurnhamBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Burnham Buckinghamshire"
      description="Professional roof maintenance services in Burnham Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Burnham Buckinghamshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInBurnhamBuckinghamshire;
