import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInMarstonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Marston Oxfordshire"
      description="Professional roof installation services in Marston Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Marston Oxfordshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInMarstonOxfordshire;
