import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInLymingtonHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Lymington Hampshire"
      description="Professional roof inspection services in Lymington Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Lymington Hampshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInLymingtonHampshire;
