import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInMarlboroughWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Marlborough Wiltshire"
      description="Professional roof maintenance services in Marlborough Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Marlborough Wiltshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInMarlboroughWiltshire;
