import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInHorshamWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Horsham West Sussex"
      description="Professional roof installation services in Horsham West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Horsham West Sussex"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInHorshamWestSussex;
