import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInWinchesterHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Winchester Hampshire"
      description="Professional roof maintenance services in Winchester Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Winchester Hampshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInWinchesterHampshire;
