import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInSouthamptonHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Southampton Hampshire"
      description="Professional roof inspection services in Southampton Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Southampton Hampshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInSouthamptonHampshire;
