import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInEpsomSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Epsom Surrey"
      description="Professional roof maintenance services in Epsom Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Epsom Surrey"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInEpsomSurrey;
