import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInPortsmouthHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Portsmouth Hampshire"
      description="Professional roof maintenance services in Portsmouth Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Portsmouth Hampshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInPortsmouthHampshire;
