import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInAltonHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Alton Hampshire"
      description="Professional roof inspection services in Alton Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Alton Hampshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInAltonHampshire;
