import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInTottonHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Totton Hampshire"
      description="Professional roof installation services in Totton Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Totton Hampshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInTottonHampshire;
