import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInEastleighHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Eastleigh Hampshire"
      description="Professional roof maintenance services in Eastleigh Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Eastleigh Hampshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInEastleighHampshire;
