import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInSouthamptonHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Southampton Hampshire"
      description="Professional roof maintenance services in Southampton Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Southampton Hampshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInSouthamptonHampshire;
