import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInRustingtonWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Rustington West Sussex"
      description="Professional roof inspection services in Rustington West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Rustington West Sussex"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInRustingtonWestSussex;
