import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInEynshamOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Eynsham Oxfordshire"
      description="Professional roof maintenance services in Eynsham Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Eynsham Oxfordshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInEynshamOxfordshire;
