import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInNailsworthGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Nailsworth Gloucestershire"
      description="Professional roof inspection services in Nailsworth Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Nailsworth Gloucestershire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInNailsworthGloucestershire;
