import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInBerkeleyGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Berkeley Gloucestershire"
      description="Professional roof inspection services in Berkeley Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Berkeley Gloucestershire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInBerkeleyGloucestershire;
