import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInSloughBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Slough Berkshire"
      description="Professional roof inspection services in Slough Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Slough Berkshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInSloughBerkshire;
