import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInCowleyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Cowley Oxfordshire"
      description="Professional roof inspection services in Cowley Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Cowley Oxfordshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInCowleyOxfordshire;
