import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInNailsworthGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Nailsworth Gloucestershire"
      description="Professional roof maintenance services in Nailsworth Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Nailsworth Gloucestershire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInNailsworthGloucestershire;
