import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInMarlboroughWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Marlborough Wiltshire"
      description="Professional roof inspection services in Marlborough Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Marlborough Wiltshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInMarlboroughWiltshire;
