import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInAndoverHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Andover Hampshire"
      description="Professional roof maintenance services in Andover Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Andover Hampshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInAndoverHampshire;
