import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInDidcotOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Didcot Oxfordshire"
      description="Professional roof maintenance services in Didcot Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Didcot Oxfordshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInDidcotOxfordshire;
