import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInRingwoodHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Ringwood Hampshire"
      description="Professional roof installation services in Ringwood Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Ringwood Hampshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInRingwoodHampshire;
