import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInWendoverBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Wendover Buckinghamshire"
      description="Professional roof inspection services in Wendover Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Wendover Buckinghamshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInWendoverBuckinghamshire;
