import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInBansteadSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Banstead Surrey"
      description="Professional roof installation services in Banstead Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Banstead Surrey"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInBansteadSurrey;
