import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInFairfordGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Fairford Gloucestershire"
      description="Professional roof inspection services in Fairford Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Fairford Gloucestershire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInFairfordGloucestershire;
