import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInHavantHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Havant Hampshire"
      description="Professional roof maintenance services in Havant Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Havant Hampshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInHavantHampshire;
