import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInAylesburyBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Aylesbury Buckinghamshire"
      description="Professional roof inspection services in Aylesbury Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Aylesbury Buckinghamshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInAylesburyBuckinghamshire;
