import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInCartertonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Carterton Oxfordshire"
      description="Professional roof inspection services in Carterton Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Carterton Oxfordshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInCartertonOxfordshire;
