import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInTidworthWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Tidworth Wiltshire"
      description="Professional roof maintenance services in Tidworth Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Tidworth Wiltshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInTidworthWiltshire;
