import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInAylesburyBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Aylesbury Buckinghamshire"
      description="Professional roof maintenance services in Aylesbury Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Aylesbury Buckinghamshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInAylesburyBuckinghamshire;
