import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInMidhurstWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Midhurst West Sussex"
      description="Professional roof inspection services in Midhurst West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Midhurst West Sussex"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInMidhurstWestSussex;
