import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInStonyStratfordBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Stony Stratford Buckinghamshire"
      description="Professional roof installation services in Stony Stratford Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Stony Stratford Buckinghamshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInStonyStratfordBuckinghamshire;
