import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInTetburyGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Tetbury Gloucestershire"
      description="Professional roof maintenance services in Tetbury Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Tetbury Gloucestershire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInTetburyGloucestershire;
