import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInWoodstockOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Woodstock Oxfordshire"
      description="Professional roof installation services in Woodstock Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Woodstock Oxfordshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInWoodstockOxfordshire;
