import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInCorshamWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Corsham Wiltshire"
      description="Professional roof inspection services in Corsham Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Corsham Wiltshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInCorshamWiltshire;
