import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInWatlingtonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Watlington Oxfordshire"
      description="Professional roof inspection services in Watlington Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Watlington Oxfordshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInWatlingtonOxfordshire;
