import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInHorshamWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Horsham West Sussex"
      description="Professional roof inspection services in Horsham West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Horsham West Sussex"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInHorshamWestSussex;
