import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInPrincesRisboroughBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Princes Risborough Buckinghamshire"
      description="Professional roof maintenance services in Princes Risborough Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Princes Risborough Buckinghamshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInPrincesRisboroughBuckinghamshire;
