import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInCheltenhamGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Cheltenham Gloucestershire"
      description="Professional roof installation services in Cheltenham Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Cheltenham Gloucestershire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInCheltenhamGloucestershire;
