import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInBerkeleyGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Berkeley Gloucestershire"
      description="Professional roof installation services in Berkeley Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Berkeley Gloucestershire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInBerkeleyGloucestershire;
