import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInGerrardsCrossBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Gerrards Cross Buckinghamshire"
      description="Professional roof installation services in Gerrards Cross Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Gerrards Cross Buckinghamshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInGerrardsCrossBuckinghamshire;
