import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInCranleighSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Cranleigh Surrey"
      description="Professional roof maintenance services in Cranleigh Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Cranleigh Surrey"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInCranleighSurrey;
