import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInBicesterOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Bicester Oxfordshire"
      description="Professional roof maintenance services in Bicester Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Bicester Oxfordshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInBicesterOxfordshire;
