import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInHaslemereSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Haslemere Surrey"
      description="Professional roof maintenance services in Haslemere Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Haslemere Surrey"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInHaslemereSurrey;
