import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInWinslowBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Winslow Buckinghamshire"
      description="Professional roof installation services in Winslow Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Winslow Buckinghamshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInWinslowBuckinghamshire;
