import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInSalisburyWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Salisbury Wiltshire"
      description="Professional roof inspection services in Salisbury Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Salisbury Wiltshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInSalisburyWiltshire;
