import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInTidworthWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Tidworth Wiltshire"
      description="Professional roof inspection services in Tidworth Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Tidworth Wiltshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInTidworthWiltshire;
