import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInWolvercoteOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Wolvercote Oxfordshire"
      description="Professional roof installation services in Wolvercote Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Wolvercote Oxfordshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInWolvercoteOxfordshire;
