import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInBurgessHillWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Burgess Hill West Sussex"
      description="Professional roof maintenance services in Burgess Hill West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Burgess Hill West Sussex"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInBurgessHillWestSussex;
