import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInEsherSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Esher Surrey"
      description="Professional roof inspection services in Esher Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Esher Surrey"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInEsherSurrey;
