import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInTidworthWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Tidworth Wiltshire"
      description="Professional roof installation services in Tidworth Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Tidworth Wiltshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInTidworthWiltshire;
