import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInChippenhamWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Chippenham Wiltshire"
      description="Professional roof installation services in Chippenham Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Chippenham Wiltshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInChippenhamWiltshire;
