import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInLittlehamptonWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Littlehampton West Sussex"
      description="Professional roof maintenance services in Littlehampton West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Littlehampton West Sussex"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInLittlehamptonWestSussex;
