import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInStroudGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Stroud Gloucestershire"
      description="Professional roof installation services in Stroud Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Stroud Gloucestershire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInStroudGloucestershire;
