import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInOlneyBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Olney Buckinghamshire"
      description="Professional roof inspection services in Olney Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Olney Buckinghamshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInOlneyBuckinghamshire;
