import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInDursleyGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Dursley Gloucestershire"
      description="Professional roof installation services in Dursley Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Dursley Gloucestershire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInDursleyGloucestershire;
