import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInBurnhamBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Burnham Buckinghamshire"
      description="Professional roof installation services in Burnham Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Burnham Buckinghamshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInBurnhamBuckinghamshire;
