import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInThameOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Thame Oxfordshire"
      description="Professional roof installation services in Thame Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Thame Oxfordshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInThameOxfordshire;
