import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInTottonHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Totton Hampshire"
      description="Professional roof maintenance services in Totton Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Totton Hampshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInTottonHampshire;
