import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInChippingNortonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Chipping Norton Oxfordshire"
      description="Professional roof installation services in Chipping Norton Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Chipping Norton Oxfordshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInChippingNortonOxfordshire;
