import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInLeatherheadSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Leatherhead Surrey"
      description="Professional roof maintenance services in Leatherhead Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Leatherhead Surrey"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInLeatherheadSurrey;
