import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInNewburyBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Newbury Berkshire"
      description="Professional roof maintenance services in Newbury Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Newbury Berkshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInNewburyBerkshire;
