import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInNewburyBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Newbury Berkshire"
      description="Professional roof installation services in Newbury Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Newbury Berkshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInNewburyBerkshire;
