import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInFarehamHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Fareham Hampshire"
      description="Professional roof installation services in Fareham Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Fareham Hampshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInFarehamHampshire;
