import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInWallingfordOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Wallingford Oxfordshire"
      description="Professional roof inspection services in Wallingford Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Wallingford Oxfordshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInWallingfordOxfordshire;
