import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInReadingBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Reading Berkshire"
      description="Professional roof installation services in Reading Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Reading Berkshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInReadingBerkshire;
