import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInWarminsterWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Warminster Wiltshire"
      description="Professional roof installation services in Warminster Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Warminster Wiltshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInWarminsterWiltshire;
