import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInChichesterWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Chichester West Sussex"
      description="Professional roof inspection services in Chichester West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Chichester West Sussex"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInChichesterWestSussex;
