import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInHavantHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Havant Hampshire"
      description="Professional roof inspection services in Havant Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Havant Hampshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInHavantHampshire;
