import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInBognorRegisWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Bognor Regis West Sussex"
      description="Professional roof maintenance services in Bognor Regis West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Bognor Regis West Sussex"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInBognorRegisWestSussex;
