import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInBognorRegisWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Bognor Regis West Sussex"
      description="Professional roof inspection services in Bognor Regis West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Bognor Regis West Sussex"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInBognorRegisWestSussex;
