import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInStroudGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Stroud Gloucestershire"
      description="Professional roof maintenance services in Stroud Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Stroud Gloucestershire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInStroudGloucestershire;
