import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInSloughBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Slough Berkshire"
      description="Professional roof installation services in Slough Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Slough Berkshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInSloughBerkshire;
