import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInHenfieldWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Henfield West Sussex"
      description="Professional roof installation services in Henfield West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Henfield West Sussex"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInHenfieldWestSussex;
