import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInShorehamBySeaWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Shoreham By Sea West Sussex"
      description="Professional roof maintenance services in Shoreham By Sea West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Shoreham By Sea West Sussex"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInShorehamBySeaWestSussex;
