import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInKidlingtonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Kidlington Oxfordshire"
      description="Professional roof inspection services in Kidlington Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Kidlington Oxfordshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInKidlingtonOxfordshire;
