import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInStonyStratfordBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Stony Stratford Buckinghamshire"
      description="Professional roof inspection services in Stony Stratford Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Stony Stratford Buckinghamshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInStonyStratfordBuckinghamshire;
