import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInWinchesterHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Winchester Hampshire"
      description="Professional roof installation services in Winchester Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Winchester Hampshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInWinchesterHampshire;
