import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInChalfontStPeterBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Chalfont St Peter Buckinghamshire"
      description="Professional roof maintenance services in Chalfont St Peter Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Chalfont St Peter Buckinghamshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInChalfontStPeterBuckinghamshire;
