import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInEastGrinsteadWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in East Grinstead West Sussex"
      description="Professional roof inspection services in East Grinstead West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="East Grinstead West Sussex"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInEastGrinsteadWestSussex;
