import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInWinchesterHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Winchester Hampshire"
      description="Professional roof inspection services in Winchester Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Winchester Hampshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInWinchesterHampshire;
