import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInWoodstockOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Woodstock Oxfordshire"
      description="Professional roof inspection services in Woodstock Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Woodstock Oxfordshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInWoodstockOxfordshire;
