import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInWeybridgeSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Weybridge Surrey"
      description="Professional roof installation services in Weybridge Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Weybridge Surrey"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInWeybridgeSurrey;
