import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInWendoverBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Wendover Buckinghamshire"
      description="Professional roof maintenance services in Wendover Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Wendover Buckinghamshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInWendoverBuckinghamshire;
