import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInRoyalWoottonBassettWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Royal Wootton Bassett Wiltshire"
      description="Professional roof inspection services in Royal Wootton Bassett Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Royal Wootton Bassett Wiltshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInRoyalWoottonBassettWiltshire;
