import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInPetworthWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Petworth West Sussex"
      description="Professional roof inspection services in Petworth West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Petworth West Sussex"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInPetworthWestSussex;
