import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInBansteadSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Banstead Surrey"
      description="Professional roof maintenance services in Banstead Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Banstead Surrey"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInBansteadSurrey;
