import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInChippingNortonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Chipping Norton Oxfordshire"
      description="Professional roof inspection services in Chipping Norton Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Chipping Norton Oxfordshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInChippingNortonOxfordshire;
