import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInWestburyWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Westbury Wiltshire"
      description="Professional roof installation services in Westbury Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Westbury Wiltshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInWestburyWiltshire;
