import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInFaringdonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Faringdon Oxfordshire"
      description="Professional roof maintenance services in Faringdon Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Faringdon Oxfordshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInFaringdonOxfordshire;
