import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInAltonHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Alton Hampshire"
      description="Professional roof maintenance services in Alton Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Alton Hampshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInAltonHampshire;
