import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInTottonHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Totton Hampshire"
      description="Professional roof inspection services in Totton Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Totton Hampshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInTottonHampshire;
