import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInStainesSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Staines Surrey"
      description="Professional roof inspection services in Staines Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Staines Surrey"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInStainesSurrey;
