import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInSalisburyWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Salisbury Wiltshire"
      description="Professional roof installation services in Salisbury Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Salisbury Wiltshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInSalisburyWiltshire;
