import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInRoseHillOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Rose Hill Oxfordshire"
      description="Professional roof maintenance services in Rose Hill Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Rose Hill Oxfordshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInRoseHillOxfordshire;
