import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInRedhillSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Redhill Surrey"
      description="Professional roof inspection services in Redhill Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Redhill Surrey"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInRedhillSurrey;
