import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInCalneWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Calne Wiltshire"
      description="Professional roof installation services in Calne Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Calne Wiltshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInCalneWiltshire;
