import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInWoodstockOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Woodstock Oxfordshire"
      description="Professional roof maintenance services in Woodstock Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Woodstock Oxfordshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInWoodstockOxfordshire;
