import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInBradfordOnAvonWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Bradford On Avon Wiltshire"
      description="Professional roof maintenance services in Bradford On Avon Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Bradford On Avon Wiltshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInBradfordOnAvonWiltshire;
