import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInNailsworthGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Nailsworth Gloucestershire"
      description="Professional roof installation services in Nailsworth Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Nailsworth Gloucestershire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInNailsworthGloucestershire;
