import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInFleetHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Fleet Hampshire"
      description="Professional roof inspection services in Fleet Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Fleet Hampshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInFleetHampshire;
