import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInWorthingWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Worthing West Sussex"
      description="Professional roof inspection services in Worthing West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Worthing West Sussex"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInWorthingWestSussex;
