import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInOlneyBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Olney Buckinghamshire"
      description="Professional roof installation services in Olney Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Olney Buckinghamshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInOlneyBuckinghamshire;
