import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInWantageOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Wantage Oxfordshire"
      description="Professional roof installation services in Wantage Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Wantage Oxfordshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInWantageOxfordshire;
