import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInStowOnTheWoldGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Stow On The Wold Gloucestershire"
      description="Professional roof maintenance services in Stow On The Wold Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Stow On The Wold Gloucestershire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInStowOnTheWoldGloucestershire;
