import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInCheltenhamGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Cheltenham Gloucestershire"
      description="Professional roof maintenance services in Cheltenham Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Cheltenham Gloucestershire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInCheltenhamGloucestershire;
