import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInPetersfieldHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Petersfield Hampshire"
      description="Professional roof inspection services in Petersfield Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Petersfield Hampshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInPetersfieldHampshire;
