import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInGodalmingSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Godalming Surrey"
      description="Professional roof installation services in Godalming Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Godalming Surrey"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInGodalmingSurrey;
