import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInCheshamBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Chesham Buckinghamshire"
      description="Professional roof installation services in Chesham Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Chesham Buckinghamshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInCheshamBuckinghamshire;
