import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInCartertonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Carterton Oxfordshire"
      description="Professional roof maintenance services in Carterton Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Carterton Oxfordshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInCartertonOxfordshire;
