import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInAbingdonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Abingdon Oxfordshire"
      description="Professional roof installation services in Abingdon Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Abingdon Oxfordshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInAbingdonOxfordshire;
