import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInEghamSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Egham Surrey"
      description="Professional roof inspection services in Egham Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Egham Surrey"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInEghamSurrey;
