import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInEastleighHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Eastleigh Hampshire"
      description="Professional roof inspection services in Eastleigh Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Eastleigh Hampshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInEastleighHampshire;
