import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInLeatherheadSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Leatherhead Surrey"
      description="Professional roof inspection services in Leatherhead Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Leatherhead Surrey"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInLeatherheadSurrey;
