import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInChalfontStPeterBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Chalfont St Peter Buckinghamshire"
      description="Professional roof inspection services in Chalfont St Peter Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Chalfont St Peter Buckinghamshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInChalfontStPeterBuckinghamshire;
