import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInDevizesWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Devizes Wiltshire"
      description="Professional roof installation services in Devizes Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Devizes Wiltshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInDevizesWiltshire;
