import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInDursleyGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Dursley Gloucestershire"
      description="Professional roof inspection services in Dursley Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Dursley Gloucestershire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInDursleyGloucestershire;
