import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInDevizesWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Devizes Wiltshire"
      description="Professional roof inspection services in Devizes Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Devizes Wiltshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInDevizesWiltshire;
