import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInFarehamHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Fareham Hampshire"
      description="Professional roof inspection services in Fareham Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Fareham Hampshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInFarehamHampshire;
