import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInMoretonInMarshGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Moreton In Marsh Gloucestershire"
      description="Professional roof installation services in Moreton In Marsh Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Moreton In Marsh Gloucestershire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInMoretonInMarshGloucestershire;
