import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInCirencesterGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Cirencester Gloucestershire"
      description="Professional roof installation services in Cirencester Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Cirencester Gloucestershire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInCirencesterGloucestershire;
