import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInWottonUnderEdgeGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Wotton Under Edge Gloucestershire"
      description="Professional roof installation services in Wotton Under Edge Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Wotton Under Edge Gloucestershire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInWottonUnderEdgeGloucestershire;
