import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInMidhurstWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Midhurst West Sussex"
      description="Professional roof installation services in Midhurst West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Midhurst West Sussex"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInMidhurstWestSussex;
