import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInMalmesburyWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Malmesbury Wiltshire"
      description="Professional roof inspection services in Malmesbury Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Malmesbury Wiltshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInMalmesburyWiltshire;
