import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInMaidenheadBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Maidenhead Berkshire"
      description="Professional roof installation services in Maidenhead Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Maidenhead Berkshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInMaidenheadBerkshire;
