import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInLeatherheadSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Leatherhead Surrey"
      description="Professional roof installation services in Leatherhead Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Leatherhead Surrey"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInLeatherheadSurrey;
