import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInCrawleyWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Crawley West Sussex"
      description="Professional roof inspection services in Crawley West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Crawley West Sussex"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInCrawleyWestSussex;
