import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInCowleyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Cowley Oxfordshire"
      description="Professional roof maintenance services in Cowley Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Cowley Oxfordshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInCowleyOxfordshire;
