import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInGloucesterGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Gloucester Gloucestershire"
      description="Professional roof maintenance services in Gloucester Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Gloucester Gloucestershire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInGloucesterGloucestershire;
