import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInChippingCampdenGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Chipping Campden Gloucestershire"
      description="Professional roof maintenance services in Chipping Campden Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Chipping Campden Gloucestershire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInChippingCampdenGloucestershire;
