import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInSelseyWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Selsey West Sussex"
      description="Professional roof installation services in Selsey West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Selsey West Sussex"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInSelseyWestSussex;
