import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInBeaconsfieldBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Beaconsfield Buckinghamshire"
      description="Professional roof maintenance services in Beaconsfield Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Beaconsfield Buckinghamshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInBeaconsfieldBuckinghamshire;
