import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInCamberleySurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Camberley Surrey"
      description="Professional roof inspection services in Camberley Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Camberley Surrey"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInCamberleySurrey;
