import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInTewkesburyGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Tewkesbury Gloucestershire"
      description="Professional roof maintenance services in Tewkesbury Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Tewkesbury Gloucestershire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInTewkesburyGloucestershire;
