import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInEghamSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Egham Surrey"
      description="Professional roof installation services in Egham Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Egham Surrey"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInEghamSurrey;
