import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInPewseyWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Pewsey Wiltshire"
      description="Professional roof installation services in Pewsey Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Pewsey Wiltshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInPewseyWiltshire;
