import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInCheshamBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Chesham Buckinghamshire"
      description="Professional roof inspection services in Chesham Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Chesham Buckinghamshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInCheshamBuckinghamshire;
