import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInOlneyBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Olney Buckinghamshire"
      description="Professional roof maintenance services in Olney Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Olney Buckinghamshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInOlneyBuckinghamshire;
