import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInChippingCampdenGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Chipping Campden Gloucestershire"
      description="Professional roof inspection services in Chipping Campden Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Chipping Campden Gloucestershire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInChippingCampdenGloucestershire;
