import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInReigateSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Reigate Surrey"
      description="Professional roof installation services in Reigate Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Reigate Surrey"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInReigateSurrey;
