import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInMelkshamWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Melksham Wiltshire"
      description="Professional roof installation services in Melksham Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Melksham Wiltshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInMelkshamWiltshire;
