import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInDorkingSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Dorking Surrey"
      description="Professional roof maintenance services in Dorking Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Dorking Surrey"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInDorkingSurrey;
