import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInFairfordGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Fairford Gloucestershire"
      description="Professional roof maintenance services in Fairford Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Fairford Gloucestershire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInFairfordGloucestershire;
