import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInWottonUnderEdgeGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Wotton Under Edge Gloucestershire"
      description="Professional roof inspection services in Wotton Under Edge Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Wotton Under Edge Gloucestershire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInWottonUnderEdgeGloucestershire;
