import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInPetersfieldHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Petersfield Hampshire"
      description="Professional roof maintenance services in Petersfield Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Petersfield Hampshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInPetersfieldHampshire;
