import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInWendoverBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Wendover Buckinghamshire"
      description="Professional roof installation services in Wendover Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Wendover Buckinghamshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInWendoverBuckinghamshire;
