import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInChippenhamWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Chippenham Wiltshire"
      description="Professional roof maintenance services in Chippenham Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Chippenham Wiltshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInChippenhamWiltshire;
