import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInSteyningWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Steyning West Sussex"
      description="Professional roof installation services in Steyning West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Steyning West Sussex"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInSteyningWestSussex;
