import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInTewkesburyGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Tewkesbury Gloucestershire"
      description="Professional roof installation services in Tewkesbury Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Tewkesbury Gloucestershire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInTewkesburyGloucestershire;
