import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInMoretonInMarshGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Moreton In Marsh Gloucestershire"
      description="Professional roof inspection services in Moreton In Marsh Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Moreton In Marsh Gloucestershire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInMoretonInMarshGloucestershire;
