import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInCharlburyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Charlbury Oxfordshire"
      description="Professional roof installation services in Charlbury Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Charlbury Oxfordshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInCharlburyOxfordshire;
