import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInJerichoOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Jericho Oxfordshire"
      description="Professional roof inspection services in Jericho Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Jericho Oxfordshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInJerichoOxfordshire;
