import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInChippingNortonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Chipping Norton Oxfordshire"
      description="Professional roof maintenance services in Chipping Norton Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Chipping Norton Oxfordshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInChippingNortonOxfordshire;
