import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInCrickladeWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Cricklade Wiltshire"
      description="Professional roof inspection services in Cricklade Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Cricklade Wiltshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInCrickladeWiltshire;
