import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInWorthingWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Worthing West Sussex"
      description="Professional roof maintenance services in Worthing West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Worthing West Sussex"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInWorthingWestSussex;
