import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInMiltonKeynesBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Milton Keynes Buckinghamshire"
      description="Professional roof installation services in Milton Keynes Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Milton Keynes Buckinghamshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInMiltonKeynesBuckinghamshire;
