import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInWestburyWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Westbury Wiltshire"
      description="Professional roof maintenance services in Westbury Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Westbury Wiltshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInWestburyWiltshire;
