import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInSwindonWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Swindon Wiltshire"
      description="Professional roof inspection services in Swindon Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Swindon Wiltshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInSwindonWiltshire;
