import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInSloughBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Slough Berkshire"
      description="Professional roof maintenance services in Slough Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Slough Berkshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInSloughBerkshire;
