import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInCowleyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Cowley Oxfordshire"
      description="Professional roof installation services in Cowley Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Cowley Oxfordshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInCowleyOxfordshire;
