import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInAmesburyWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Amesbury Wiltshire"
      description="Professional roof installation services in Amesbury Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Amesbury Wiltshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInAmesburyWiltshire;
