import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInCorshamWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Corsham Wiltshire"
      description="Professional roof maintenance services in Corsham Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Corsham Wiltshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInCorshamWiltshire;
