import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInCharlburyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Charlbury Oxfordshire"
      description="Professional roof inspection services in Charlbury Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Charlbury Oxfordshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInCharlburyOxfordshire;
