import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInCranleighSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Cranleigh Surrey"
      description="Professional roof inspection services in Cranleigh Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Cranleigh Surrey"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInCranleighSurrey;
