import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInHorleySurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Horley Surrey"
      description="Professional roof inspection services in Horley Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Horley Surrey"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInHorleySurrey;
