import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInSouthwickWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Southwick West Sussex"
      description="Professional roof inspection services in Southwick West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Southwick West Sussex"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInSouthwickWestSussex;
