import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInEastGrinsteadWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in East Grinstead West Sussex"
      description="Professional roof maintenance services in East Grinstead West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="East Grinstead West Sussex"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInEastGrinsteadWestSussex;
