import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInWokingSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Woking Surrey"
      description="Professional roof inspection services in Woking Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Woking Surrey"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInWokingSurrey;
