import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInFarnboroughHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Farnborough Hampshire"
      description="Professional roof maintenance services in Farnborough Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Farnborough Hampshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInFarnboroughHampshire;
