import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInWinchcombeGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Winchcombe Gloucestershire"
      description="Professional roof inspection services in Winchcombe Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Winchcombe Gloucestershire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInWinchcombeGloucestershire;
