import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInPetworthWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Petworth West Sussex"
      description="Professional roof installation services in Petworth West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Petworth West Sussex"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInPetworthWestSussex;
