import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInMarlowBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Marlow Buckinghamshire"
      description="Professional roof inspection services in Marlow Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Marlow Buckinghamshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInMarlowBuckinghamshire;
