import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInHaywardsHeathWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Haywards Heath West Sussex"
      description="Professional roof inspection services in Haywards Heath West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Haywards Heath West Sussex"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInHaywardsHeathWestSussex;
