import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInCorshamWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Corsham Wiltshire"
      description="Professional roof installation services in Corsham Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Corsham Wiltshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInCorshamWiltshire;
