import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInLittlehamptonWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Littlehampton West Sussex"
      description="Professional roof installation services in Littlehampton West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Littlehampton West Sussex"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInLittlehamptonWestSussex;
