import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInBurnhamBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Burnham Buckinghamshire"
      description="Professional roof inspection services in Burnham Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Burnham Buckinghamshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInBurnhamBuckinghamshire;
