import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInWiltonWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Wilton Wiltshire"
      description="Professional roof maintenance services in Wilton Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Wilton Wiltshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInWiltonWiltshire;
