import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInHighWycombeBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in High Wycombe Buckinghamshire"
      description="Professional roof installation services in High Wycombe Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="High Wycombe Buckinghamshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInHighWycombeBuckinghamshire;
