import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInDorkingSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Dorking Surrey"
      description="Professional roof inspection services in Dorking Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Dorking Surrey"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInDorkingSurrey;
