import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInMarlboroughWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Marlborough Wiltshire"
      description="Professional roof installation services in Marlborough Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Marlborough Wiltshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInMarlboroughWiltshire;
