import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInWinchcombeGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Winchcombe Gloucestershire"
      description="Professional roof maintenance services in Winchcombe Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Winchcombe Gloucestershire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInWinchcombeGloucestershire;
