import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInAmesburyWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Amesbury Wiltshire"
      description="Professional roof maintenance services in Amesbury Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Amesbury Wiltshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInAmesburyWiltshire;
