import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInBeaconsfieldBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Beaconsfield Buckinghamshire"
      description="Professional roof installation services in Beaconsfield Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Beaconsfield Buckinghamshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInBeaconsfieldBuckinghamshire;
