import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInAbingdonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Abingdon Oxfordshire"
      description="Professional roof inspection services in Abingdon Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Abingdon Oxfordshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInAbingdonOxfordshire;
