import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInSalisburyWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Salisbury Wiltshire"
      description="Professional roof maintenance services in Salisbury Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Salisbury Wiltshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInSalisburyWiltshire;
