import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInGreatMissendenBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Great Missenden Buckinghamshire"
      description="Professional roof maintenance services in Great Missenden Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Great Missenden Buckinghamshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInGreatMissendenBuckinghamshire;
