import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInStowOnTheWoldGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Stow On The Wold Gloucestershire"
      description="Professional roof installation services in Stow On The Wold Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Stow On The Wold Gloucestershire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInStowOnTheWoldGloucestershire;
