import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInWantageOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Wantage Oxfordshire"
      description="Professional roof maintenance services in Wantage Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Wantage Oxfordshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInWantageOxfordshire;
