import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInEghamSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Egham Surrey"
      description="Professional roof maintenance services in Egham Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Egham Surrey"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInEghamSurrey;
