import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInTrowbridgeWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Trowbridge Wiltshire"
      description="Professional roof inspection services in Trowbridge Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Trowbridge Wiltshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInTrowbridgeWiltshire;
