import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInWantageOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Wantage Oxfordshire"
      description="Professional roof inspection services in Wantage Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Wantage Oxfordshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInWantageOxfordshire;
