import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInSwindonWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Swindon Wiltshire"
      description="Professional roof installation services in Swindon Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Swindon Wiltshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInSwindonWiltshire;
