import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInWottonUnderEdgeGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Wotton Under Edge Gloucestershire"
      description="Professional roof maintenance services in Wotton Under Edge Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Wotton Under Edge Gloucestershire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInWottonUnderEdgeGloucestershire;
