import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInWolvercoteOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Wolvercote Oxfordshire"
      description="Professional roof inspection services in Wolvercote Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Wolvercote Oxfordshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInWolvercoteOxfordshire;
