import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInChalfontStPeterBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Chalfont St Peter Buckinghamshire"
      description="Professional roof installation services in Chalfont St Peter Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Chalfont St Peter Buckinghamshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInChalfontStPeterBuckinghamshire;
