import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInWarminsterWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Warminster Wiltshire"
      description="Professional roof inspection services in Warminster Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Warminster Wiltshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInWarminsterWiltshire;
