import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInGodalmingSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Godalming Surrey"
      description="Professional roof maintenance services in Godalming Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Godalming Surrey"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInGodalmingSurrey;
