import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInDorkingSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Dorking Surrey"
      description="Professional roof installation services in Dorking Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Dorking Surrey"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInDorkingSurrey;
