import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInSouthamptonHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Southampton Hampshire"
      description="Professional roof installation services in Southampton Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Southampton Hampshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInSouthamptonHampshire;
