import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInWeybridgeSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Weybridge Surrey"
      description="Professional roof maintenance services in Weybridge Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Weybridge Surrey"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInWeybridgeSurrey;
