import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInHaywardsHeathWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Haywards Heath West Sussex"
      description="Professional roof maintenance services in Haywards Heath West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Haywards Heath West Sussex"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInHaywardsHeathWestSussex;
