import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInTrowbridgeWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Trowbridge Wiltshire"
      description="Professional roof installation services in Trowbridge Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Trowbridge Wiltshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInTrowbridgeWiltshire;
