import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInWarminsterWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Warminster Wiltshire"
      description="Professional roof maintenance services in Warminster Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Warminster Wiltshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInWarminsterWiltshire;
