import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInShorehamBySeaWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Shoreham By Sea West Sussex"
      description="Professional roof installation services in Shoreham By Sea West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Shoreham By Sea West Sussex"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInShorehamBySeaWestSussex;
