import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInBradfordOnAvonWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Bradford On Avon Wiltshire"
      description="Professional roof inspection services in Bradford On Avon Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Bradford On Avon Wiltshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInBradfordOnAvonWiltshire;
