import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInHorleySurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Horley Surrey"
      description="Professional roof maintenance services in Horley Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Horley Surrey"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInHorleySurrey;
