import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInNewentGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Newent Gloucestershire"
      description="Professional roof inspection services in Newent Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Newent Gloucestershire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInNewentGloucestershire;
