import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInStainesSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Staines Surrey"
      description="Professional roof maintenance services in Staines Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Staines Surrey"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInStainesSurrey;
