import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInEynshamOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Eynsham Oxfordshire"
      description="Professional roof inspection services in Eynsham Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Eynsham Oxfordshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInEynshamOxfordshire;
