import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInBotleyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Botley Oxfordshire"
      description="Professional roof inspection services in Botley Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Botley Oxfordshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInBotleyOxfordshire;
