import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInGreatMissendenBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Great Missenden Buckinghamshire"
      description="Professional roof inspection services in Great Missenden Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Great Missenden Buckinghamshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInGreatMissendenBuckinghamshire;
