import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInGuildfordSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Guildford Surrey"
      description="Professional roof inspection services in Guildford Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Guildford Surrey"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInGuildfordSurrey;
