import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInLechladeGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Lechlade Gloucestershire"
      description="Professional roof maintenance services in Lechlade Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Lechlade Gloucestershire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInLechladeGloucestershire;
