import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInCartertonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Carterton Oxfordshire"
      description="Professional roof installation services in Carterton Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Carterton Oxfordshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInCartertonOxfordshire;
