import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInPrincesRisboroughBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Princes Risborough Buckinghamshire"
      description="Professional roof installation services in Princes Risborough Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Princes Risborough Buckinghamshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInPrincesRisboroughBuckinghamshire;
