import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInBuckinghamBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Buckingham Buckinghamshire"
      description="Professional roof maintenance services in Buckingham Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Buckingham Buckinghamshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInBuckinghamBuckinghamshire;
