import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInHighWycombeBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in High Wycombe Buckinghamshire"
      description="Professional roof inspection services in High Wycombe Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="High Wycombe Buckinghamshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInHighWycombeBuckinghamshire;
