import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInMelkshamWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Melksham Wiltshire"
      description="Professional roof maintenance services in Melksham Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Melksham Wiltshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInMelkshamWiltshire;
