import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInCharlburyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Charlbury Oxfordshire"
      description="Professional roof maintenance services in Charlbury Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Charlbury Oxfordshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInCharlburyOxfordshire;
