import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInCrawleyWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Crawley West Sussex"
      description="Professional roof installation services in Crawley West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Crawley West Sussex"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInCrawleyWestSussex;
