import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInHenleyOnThamesOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Henley On Thames Oxfordshire"
      description="Professional roof installation services in Henley On Thames Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Henley On Thames Oxfordshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInHenleyOnThamesOxfordshire;
