import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInIffleyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Iffley Oxfordshire"
      description="Professional roof maintenance services in Iffley Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Iffley Oxfordshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInIffleyOxfordshire;
