import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInJerichoOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Jericho Oxfordshire"
      description="Professional roof maintenance services in Jericho Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Jericho Oxfordshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInJerichoOxfordshire;
