import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInFarnhamSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Farnham Surrey"
      description="Professional roof maintenance services in Farnham Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Farnham Surrey"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInFarnhamSurrey;
