import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInGerrardsCrossBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Gerrards Cross Buckinghamshire"
      description="Professional roof inspection services in Gerrards Cross Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Gerrards Cross Buckinghamshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInGerrardsCrossBuckinghamshire;
