import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInWiltonWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Wilton Wiltshire"
      description="Professional roof installation services in Wilton Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Wilton Wiltshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInWiltonWiltshire;
