import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInMarlowBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Marlow Buckinghamshire"
      description="Professional roof maintenance services in Marlow Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Marlow Buckinghamshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInMarlowBuckinghamshire;
