import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInBracknellBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Bracknell Berkshire"
      description="Professional roof maintenance services in Bracknell Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Bracknell Berkshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInBracknellBerkshire;
