import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInBlackbirdLeysOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Blackbird Leys Oxfordshire"
      description="Professional roof inspection services in Blackbird Leys Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Blackbird Leys Oxfordshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInBlackbirdLeysOxfordshire;
