import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInMiltonKeynesBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Milton Keynes Buckinghamshire"
      description="Professional roof inspection services in Milton Keynes Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Milton Keynes Buckinghamshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInMiltonKeynesBuckinghamshire;
