import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInNewportPagnellBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Newport Pagnell Buckinghamshire"
      description="Professional roof installation services in Newport Pagnell Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Newport Pagnell Buckinghamshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInNewportPagnellBuckinghamshire;
