import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInAltonHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Alton Hampshire"
      description="Professional roof installation services in Alton Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Alton Hampshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInAltonHampshire;
