import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInChichesterWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Chichester West Sussex"
      description="Professional roof installation services in Chichester West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Chichester West Sussex"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInChichesterWestSussex;
