import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInEsherSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Esher Surrey"
      description="Professional roof maintenance services in Esher Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Esher Surrey"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInEsherSurrey;
