import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInReadingBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Reading Berkshire"
      description="Professional roof inspection services in Reading Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Reading Berkshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInReadingBerkshire;
