import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInKidlingtonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Kidlington Oxfordshire"
      description="Professional roof installation services in Kidlington Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Kidlington Oxfordshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInKidlingtonOxfordshire;
