import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInWolvercoteOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Wolvercote Oxfordshire"
      description="Professional roof maintenance services in Wolvercote Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Wolvercote Oxfordshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInWolvercoteOxfordshire;
