import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInWatlingtonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Watlington Oxfordshire"
      description="Professional roof maintenance services in Watlington Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Watlington Oxfordshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInWatlingtonOxfordshire;
