import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInBracknellBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Bracknell Berkshire"
      description="Professional roof installation services in Bracknell Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Bracknell Berkshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInBracknellBerkshire;
