import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInWindsorBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Windsor Berkshire"
      description="Professional roof inspection services in Windsor Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Windsor Berkshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInWindsorBerkshire;
