import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInRedhillSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Redhill Surrey"
      description="Professional roof installation services in Redhill Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Redhill Surrey"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInRedhillSurrey;
