import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInCirencesterGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Cirencester Gloucestershire"
      description="Professional roof maintenance services in Cirencester Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Cirencester Gloucestershire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInCirencesterGloucestershire;
