import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInFarnhamSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Farnham Surrey"
      description="Professional roof installation services in Farnham Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Farnham Surrey"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInFarnhamSurrey;
