import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInCamberleySurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Camberley Surrey"
      description="Professional roof maintenance services in Camberley Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Camberley Surrey"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInCamberleySurrey;
