import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInPetersfieldHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Petersfield Hampshire"
      description="Professional roof installation services in Petersfield Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Petersfield Hampshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInPetersfieldHampshire;
