import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInStonyStratfordBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Stony Stratford Buckinghamshire"
      description="Professional roof maintenance services in Stony Stratford Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Stony Stratford Buckinghamshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInStonyStratfordBuckinghamshire;
