import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInGerrardsCrossBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Gerrards Cross Buckinghamshire"
      description="Professional roof maintenance services in Gerrards Cross Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Gerrards Cross Buckinghamshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInGerrardsCrossBuckinghamshire;
