import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInMarstonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Marston Oxfordshire"
      description="Professional roof inspection services in Marston Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Marston Oxfordshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInMarstonOxfordshire;
