import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInNewentGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Newent Gloucestershire"
      description="Professional roof installation services in Newent Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Newent Gloucestershire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInNewentGloucestershire;
