import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInHeadingtonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Headington Oxfordshire"
      description="Professional roof inspection services in Headington Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Headington Oxfordshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInHeadingtonOxfordshire;
