import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInBotleyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Botley Oxfordshire"
      description="Professional roof installation services in Botley Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Botley Oxfordshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInBotleyOxfordshire;
