import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInBasingstokeHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Basingstoke Hampshire"
      description="Professional roof maintenance services in Basingstoke Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Basingstoke Hampshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInBasingstokeHampshire;
