import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInSelseyWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Selsey West Sussex"
      description="Professional roof inspection services in Selsey West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Selsey West Sussex"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInSelseyWestSussex;
