import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInWokinghamBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Wokingham Berkshire"
      description="Professional roof installation services in Wokingham Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Wokingham Berkshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInWokinghamBerkshire;
