import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInAylesburyBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Aylesbury Buckinghamshire"
      description="Professional roof installation services in Aylesbury Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Aylesbury Buckinghamshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInAylesburyBuckinghamshire;
