import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInMaidenheadBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Maidenhead Berkshire"
      description="Professional roof inspection services in Maidenhead Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Maidenhead Berkshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInMaidenheadBerkshire;
