import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInRoseHillOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Rose Hill Oxfordshire"
      description="Professional roof installation services in Rose Hill Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Rose Hill Oxfordshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInRoseHillOxfordshire;
