import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInCranleighSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Cranleigh Surrey"
      description="Professional roof installation services in Cranleigh Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Cranleigh Surrey"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInCranleighSurrey;
