import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInTrowbridgeWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Trowbridge Wiltshire"
      description="Professional roof maintenance services in Trowbridge Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Trowbridge Wiltshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInTrowbridgeWiltshire;
