import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInBeaconsfieldBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Beaconsfield Buckinghamshire"
      description="Professional roof inspection services in Beaconsfield Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Beaconsfield Buckinghamshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInBeaconsfieldBuckinghamshire;
