import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInPortsmouthHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Portsmouth Hampshire"
      description="Professional roof inspection services in Portsmouth Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Portsmouth Hampshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInPortsmouthHampshire;
