import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInCheshamBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Chesham Buckinghamshire"
      description="Professional roof maintenance services in Chesham Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Chesham Buckinghamshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInCheshamBuckinghamshire;
