import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInWinslowBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Winslow Buckinghamshire"
      description="Professional roof maintenance services in Winslow Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Winslow Buckinghamshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInWinslowBuckinghamshire;
