import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInBracknellBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Bracknell Berkshire"
      description="Professional roof inspection services in Bracknell Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Bracknell Berkshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInBracknellBerkshire;
