import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInHeadingtonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Headington Oxfordshire"
      description="Professional roof installation services in Headington Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Headington Oxfordshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInHeadingtonOxfordshire;
