import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInNewportPagnellBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Newport Pagnell Buckinghamshire"
      description="Professional roof maintenance services in Newport Pagnell Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Newport Pagnell Buckinghamshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInNewportPagnellBuckinghamshire;
