import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInSteyningWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Steyning West Sussex"
      description="Professional roof inspection services in Steyning West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Steyning West Sussex"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInSteyningWestSussex;
