import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInWitneyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Witney Oxfordshire"
      description="Professional roof installation services in Witney Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Witney Oxfordshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInWitneyOxfordshire;
