import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInAndoverHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Andover Hampshire"
      description="Professional roof installation services in Andover Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Andover Hampshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInAndoverHampshire;
