import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInMoretonInMarshGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Moreton In Marsh Gloucestershire"
      description="Professional roof maintenance services in Moreton In Marsh Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Moreton In Marsh Gloucestershire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInMoretonInMarshGloucestershire;
