import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInNewportPagnellBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Newport Pagnell Buckinghamshire"
      description="Professional roof inspection services in Newport Pagnell Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Newport Pagnell Buckinghamshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInNewportPagnellBuckinghamshire;
