import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInSelseyWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Selsey West Sussex"
      description="Professional roof maintenance services in Selsey West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Selsey West Sussex"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInSelseyWestSussex;
