import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInWallingfordOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Wallingford Oxfordshire"
      description="Professional roof installation services in Wallingford Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Wallingford Oxfordshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInWallingfordOxfordshire;
