import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInPortsmouthHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Portsmouth Hampshire"
      description="Professional roof installation services in Portsmouth Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Portsmouth Hampshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInPortsmouthHampshire;
