import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInBurgessHillWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Burgess Hill West Sussex"
      description="Professional roof inspection services in Burgess Hill West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Burgess Hill West Sussex"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInBurgessHillWestSussex;
