import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInBanburyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Banbury Oxfordshire"
      description="Professional roof maintenance services in Banbury Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Banbury Oxfordshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInBanburyOxfordshire;
