import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInFleetHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Fleet Hampshire"
      description="Professional roof maintenance services in Fleet Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Fleet Hampshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInFleetHampshire;
