import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInTewkesburyGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Tewkesbury Gloucestershire"
      description="Professional roof inspection services in Tewkesbury Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Tewkesbury Gloucestershire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInTewkesburyGloucestershire;
