import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInWatlingtonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Watlington Oxfordshire"
      description="Professional roof installation services in Watlington Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Watlington Oxfordshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInWatlingtonOxfordshire;
