import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInAmershamBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Amersham Buckinghamshire"
      description="Professional roof maintenance services in Amersham Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Amersham Buckinghamshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInAmershamBuckinghamshire;
