import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInWinslowBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Winslow Buckinghamshire"
      description="Professional roof inspection services in Winslow Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Winslow Buckinghamshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInWinslowBuckinghamshire;
