import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInDursleyGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Dursley Gloucestershire"
      description="Professional roof maintenance services in Dursley Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Dursley Gloucestershire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInDursleyGloucestershire;
