import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInCrickladeWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Cricklade Wiltshire"
      description="Professional roof installation services in Cricklade Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Cricklade Wiltshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInCrickladeWiltshire;
