import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInRomseyHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Romsey Hampshire"
      description="Professional roof maintenance services in Romsey Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Romsey Hampshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInRomseyHampshire;
