import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInBicesterOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Bicester Oxfordshire"
      description="Professional roof inspection services in Bicester Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Bicester Oxfordshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInBicesterOxfordshire;
