import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInMarlowBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Marlow Buckinghamshire"
      description="Professional roof installation services in Marlow Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Marlow Buckinghamshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInMarlowBuckinghamshire;
