import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInBuckinghamBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Buckingham Buckinghamshire"
      description="Professional roof inspection services in Buckingham Buckinghamshire. Expert local roofers, competitive pricing, and reliable service."
      location="Buckingham Buckinghamshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInBuckinghamBuckinghamshire;
