import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInReigateSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Reigate Surrey"
      description="Professional roof inspection services in Reigate Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Reigate Surrey"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInReigateSurrey;
