import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInReigateSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Reigate Surrey"
      description="Professional roof maintenance services in Reigate Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Reigate Surrey"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInReigateSurrey;
