import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInCrickladeWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Cricklade Wiltshire"
      description="Professional roof maintenance services in Cricklade Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Cricklade Wiltshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInCrickladeWiltshire;
