import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInRomseyHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Romsey Hampshire"
      description="Professional roof installation services in Romsey Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Romsey Hampshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInRomseyHampshire;
