import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInIffleyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Iffley Oxfordshire"
      description="Professional roof installation services in Iffley Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Iffley Oxfordshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInIffleyOxfordshire;
