import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInAldershotHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Aldershot Hampshire"
      description="Professional roof installation services in Aldershot Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Aldershot Hampshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInAldershotHampshire;
