import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInThameOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Thame Oxfordshire"
      description="Professional roof inspection services in Thame Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Thame Oxfordshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInThameOxfordshire;
