import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInIffleyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Iffley Oxfordshire"
      description="Professional roof inspection services in Iffley Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Iffley Oxfordshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInIffleyOxfordshire;
