import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInBicesterOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Bicester Oxfordshire"
      description="Professional roof installation services in Bicester Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Bicester Oxfordshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInBicesterOxfordshire;
