import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInSwindonWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Swindon Wiltshire"
      description="Professional roof maintenance services in Swindon Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Swindon Wiltshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInSwindonWiltshire;
