import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInHorleySurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Horley Surrey"
      description="Professional roof installation services in Horley Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Horley Surrey"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInHorleySurrey;
