import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInBlackbirdLeysOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Blackbird Leys Oxfordshire"
      description="Professional roof installation services in Blackbird Leys Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Blackbird Leys Oxfordshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInBlackbirdLeysOxfordshire;
