import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInJerichoOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Jericho Oxfordshire"
      description="Professional roof installation services in Jericho Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Jericho Oxfordshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInJerichoOxfordshire;
