import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInBlackbirdLeysOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Blackbird Leys Oxfordshire"
      description="Professional roof maintenance services in Blackbird Leys Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Blackbird Leys Oxfordshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInBlackbirdLeysOxfordshire;
