import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInSouthwickWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Southwick West Sussex"
      description="Professional roof installation services in Southwick West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Southwick West Sussex"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInSouthwickWestSussex;
