import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInRoseHillOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Rose Hill Oxfordshire"
      description="Professional roof inspection services in Rose Hill Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Rose Hill Oxfordshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInRoseHillOxfordshire;
