import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInStonehouseGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Stonehouse Gloucestershire"
      description="Professional roof installation services in Stonehouse Gloucestershire. Expert local roofers, competitive pricing, and reliable service."
      location="Stonehouse Gloucestershire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInStonehouseGloucestershire;
