import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInDidcotOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Didcot Oxfordshire"
      description="Professional roof installation services in Didcot Oxfordshire. Expert local roofers, competitive pricing, and reliable service."
      location="Didcot Oxfordshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInDidcotOxfordshire;
