import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInChichesterWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Chichester West Sussex"
      description="Professional roof maintenance services in Chichester West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Chichester West Sussex"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInChichesterWestSussex;
