import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInHaywardsHeathWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Haywards Heath West Sussex"
      description="Professional roof installation services in Haywards Heath West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Haywards Heath West Sussex"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInHaywardsHeathWestSussex;
