import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInCalneWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Calne Wiltshire"
      description="Professional roof maintenance services in Calne Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Calne Wiltshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInCalneWiltshire;
