import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInFarnboroughHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Farnborough Hampshire"
      description="Professional roof inspection services in Farnborough Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Farnborough Hampshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInFarnboroughHampshire;
