import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInBognorRegisWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Bognor Regis West Sussex"
      description="Professional roof installation services in Bognor Regis West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Bognor Regis West Sussex"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInBognorRegisWestSussex;
