import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInSteyningWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Steyning West Sussex"
      description="Professional roof maintenance services in Steyning West Sussex. Expert local roofers, competitive pricing, and reliable service."
      location="Steyning West Sussex"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInSteyningWestSussex;
