import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInPewseyWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Pewsey Wiltshire"
      description="Professional roof inspection services in Pewsey Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Pewsey Wiltshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInPewseyWiltshire;
