import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInCalneWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Calne Wiltshire"
      description="Professional roof inspection services in Calne Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Calne Wiltshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInCalneWiltshire;
