import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInGodalmingSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Godalming Surrey"
      description="Professional roof inspection services in Godalming Surrey. Expert local roofers, competitive pricing, and reliable service."
      location="Godalming Surrey"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInGodalmingSurrey;
