import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInRingwoodHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Ringwood Hampshire"
      description="Professional roof inspection services in Ringwood Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Ringwood Hampshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInRingwoodHampshire;
