import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInstallationInEastleighHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Installation in Eastleigh Hampshire"
      description="Professional roof installation services in Eastleigh Hampshire. Expert local roofers, competitive pricing, and reliable service."
      location="Eastleigh Hampshire"
      service="Roof Installation"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInstallationInEastleighHampshire;
