import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofMaintenanceInWokinghamBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Maintenance in Wokingham Berkshire"
      description="Professional roof maintenance services in Wokingham Berkshire. Expert local roofers, competitive pricing, and reliable service."
      location="Wokingham Berkshire"
      service="Roof Maintenance"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofMaintenanceInWokinghamBerkshire;
