import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const RoofInspectionInWiltonWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Roof Inspection in Wilton Wiltshire"
      description="Professional roof inspection services in Wilton Wiltshire. Expert local roofers, competitive pricing, and reliable service."
      location="Wilton Wiltshire"
      service="Roof Inspection"
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default RoofInspectionInWiltonWiltshire;
