[build]
  base = ""
  publish = ".next"
  command = "npm install && npm run build"
  node_version = "20.x"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://52roofer.com"
  NODE_VERSION = "20"
  NPM_VERSION = "9"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "text/xml"
    Cache-Control = "public, max-age=0, must-revalidate"

[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next"
