[build]
  command = "npm run build"
  publish = ".next"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "text/xml"
    Cache-Control = "public, max-age=0, must-revalidate"

[[plugins]]
  package = "@netlify/plugin-nextjs"
