[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18.19.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Rewrite rule to handle Next.js routing
[[redirects]]
  from = "/*"
  to = "/_next/static/:splat"
  status = 200
  force = false
  conditions = {Path = "/_next/static/*"}

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next_server"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' *.netlify.app; img-src 'self' data: blob: *.netlify.app; connect-src 'self' *.netlify.app script.google.com *.script.google.com; form-action 'self';"
