import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInBasingstokeHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Basingstoke Hampshire"
      description="Voice-optimized emergency roofing services in Basingstoke Hampshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Basingstoke Hampshire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInBasingstokeHampshire;
