import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInWallingfordOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Wallingford Oxfordshire"
      description="Voice-optimized emergency roofing services in Wallingford Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Wallingford Oxfordshire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInWallingfordOxfordshire;
