import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInTrowbridgeWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Trowbridge Wiltshire"
      description="Voice-optimized emergency roofing services in Trowbridge Wiltshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Trowbridge Wiltshire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInTrowbridgeWiltshire;
