import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInMiltonKeynesBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Milton Keynes Buckinghamshire"
      description="Voice-optimized emergency roofing services in Milton Keynes Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Milton Keynes Buckinghamshire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInMiltonKeynesBuckinghamshire;
