import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInChalfontStPeterBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Chalfont St Peter Buckinghamshire"
      description="Voice-optimized emergency roofing services in Chalfont St Peter Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Chalfont St Peter Buckinghamshire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInChalfontStPeterBuckinghamshire;
