import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInNewburyBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Newbury Berkshire"
      description="Voice-optimized emergency roofing services in Newbury Berkshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Newbury Berkshire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInNewburyBerkshire;
