import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInGodalmingSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Godalming Surrey"
      description="Voice-optimized emergency roofing services in Godalming Surrey. Use voice commands to get information, request quotes, and schedule appointments."
      location="Godalming Surrey"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInGodalmingSurrey;
