import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInCheltenhamGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Cheltenham Gloucestershire"
      description="Voice-optimized emergency roofing services in Cheltenham Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Cheltenham Gloucestershire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInCheltenhamGloucestershire;
