import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInRedhillSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Redhill Surrey"
      description="Voice-optimized emergency roofing services in Redhill Surrey. Use voice commands to get information, request quotes, and schedule appointments."
      location="Redhill Surrey"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInRedhillSurrey;
