import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInCranleighSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Cranleigh Surrey"
      description="Voice-optimized emergency roofing services in Cranleigh Surrey. Use voice commands to get information, request quotes, and schedule appointments."
      location="Cranleigh Surrey"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInCranleighSurrey;
