import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInStonehouseGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Stonehouse Gloucestershire"
      description="Voice-optimized emergency roofing services in Stonehouse Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Stonehouse Gloucestershire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInStonehouseGloucestershire;
