import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInCharlburyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Charlbury Oxfordshire"
      description="Voice-optimized emergency roofing services in Charlbury Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Charlbury Oxfordshire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInCharlburyOxfordshire;
