import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInTetburyGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Tetbury Gloucestershire"
      description="Voice-optimized emergency roofing services in Tetbury Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Tetbury Gloucestershire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInTetburyGloucestershire;
