import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInBuckinghamBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Buckingham Buckinghamshire"
      description="Voice-optimized emergency roofing services in Buckingham Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Buckingham Buckinghamshire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInBuckinghamBuckinghamshire;
