import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInStonyStratfordBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Stony Stratford Buckinghamshire"
      description="Voice-optimized emergency roofing services in Stony Stratford Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Stony Stratford Buckinghamshire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInStonyStratfordBuckinghamshire;
