import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInLeatherheadSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Leatherhead Surrey"
      description="Voice-optimized emergency roofing services in Leatherhead Surrey. Use voice commands to get information, request quotes, and schedule appointments."
      location="Leatherhead Surrey"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInLeatherheadSurrey;
