import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInGerrardsCrossBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Gerrards Cross Buckinghamshire"
      description="Voice-optimized emergency roofing services in Gerrards Cross Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Gerrards Cross Buckinghamshire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInGerrardsCrossBuckinghamshire;
