import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInEastleighHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Eastleigh Hampshire"
      description="Voice-optimized emergency roofing services in Eastleigh Hampshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Eastleigh Hampshire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInEastleighHampshire;
