import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInWokinghamBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Wokingham Berkshire"
      description="Voice-optimized emergency roofing services in Wokingham Berkshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Wokingham Berkshire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInWokinghamBerkshire;
