import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInChippingCampdenGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Chipping Campden Gloucestershire"
      description="Voice-optimized emergency roofing services in Chipping Campden Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Chipping Campden Gloucestershire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInChippingCampdenGloucestershire;
