import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInNewportPagnellBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Newport Pagnell Buckinghamshire"
      description="Voice-optimized emergency roofing services in Newport Pagnell Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Newport Pagnell Buckinghamshire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInNewportPagnellBuckinghamshire;
