import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInGreatMissendenBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Great Missenden Buckinghamshire"
      description="Voice-optimized emergency roofing services in Great Missenden Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Great Missenden Buckinghamshire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInGreatMissendenBuckinghamshire;
