import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInOlneyBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Olney Buckinghamshire"
      description="Voice-optimized emergency roofing services in Olney Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Olney Buckinghamshire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInOlneyBuckinghamshire;
