import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInWendoverBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Wendover Buckinghamshire"
      description="Voice-optimized emergency roofing services in Wendover Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Wendover Buckinghamshire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInWendoverBuckinghamshire;
