import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInNailsworthGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Nailsworth Gloucestershire"
      description="Voice-optimized emergency roofing services in Nailsworth Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Nailsworth Gloucestershire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInNailsworthGloucestershire;
