import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInWottonUnderEdgeGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Wotton Under Edge Gloucestershire"
      description="Voice-optimized emergency roofing services in Wotton Under Edge Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Wotton Under Edge Gloucestershire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInWottonUnderEdgeGloucestershire;
