import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInPrincesRisboroughBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Princes Risborough Buckinghamshire"
      description="Voice-optimized emergency roofing services in Princes Risborough Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Princes Risborough Buckinghamshire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInPrincesRisboroughBuckinghamshire;
