import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInWinchesterHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Winchester Hampshire"
      description="Voice-optimized emergency roofing services in Winchester Hampshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Winchester Hampshire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInWinchesterHampshire;
