import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInSummertownOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Summertown Oxfordshire"
      description="Voice-optimized emergency roofing services in Summertown Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Summertown Oxfordshire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInSummertownOxfordshire;
