import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInBurgessHillWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Burgess Hill West Sussex"
      description="Voice-optimized emergency roofing services in Burgess Hill West Sussex. Use voice commands to get information, request quotes, and schedule appointments."
      location="Burgess Hill West Sussex"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInBurgessHillWestSussex;
