import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInHighWycombeBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in High Wycombe Buckinghamshire"
      description="Voice-optimized emergency roofing services in High Wycombe Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="High Wycombe Buckinghamshire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInHighWycombeBuckinghamshire;
