import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInShorehamBySeaWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Shoreham By Sea West Sussex"
      description="Voice-optimized emergency roofing services in Shoreham By Sea West Sussex. Use voice commands to get information, request quotes, and schedule appointments."
      location="Shoreham By Sea West Sussex"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInShorehamBySeaWestSussex;
