import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInRoseHillOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Rose Hill Oxfordshire"
      description="Voice-optimized emergency roofing services in Rose Hill Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Rose Hill Oxfordshire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInRoseHillOxfordshire;
