import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInHenleyOnThamesOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Henley On Thames Oxfordshire"
      description="Voice-optimized emergency roofing services in Henley On Thames Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Henley On Thames Oxfordshire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInHenleyOnThamesOxfordshire;
