import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInPetersfieldHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Petersfield Hampshire"
      description="Voice-optimized emergency roofing services in Petersfield Hampshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Petersfield Hampshire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInPetersfieldHampshire;
