import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInWeybridgeSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Weybridge Surrey"
      description="Voice-optimized emergency roofing services in Weybridge Surrey. Use voice commands to get information, request quotes, and schedule appointments."
      location="Weybridge Surrey"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInWeybridgeSurrey;
