import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInCheshamBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Chesham Buckinghamshire"
      description="Voice-optimized emergency roofing services in Chesham Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Chesham Buckinghamshire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInCheshamBuckinghamshire;
