import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInSwindonWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Swindon Wiltshire"
      description="Voice-optimized emergency roofing services in Swindon Wiltshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Swindon Wiltshire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInSwindonWiltshire;
