import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInStowOnTheWoldGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Stow On The Wold Gloucestershire"
      description="Voice-optimized emergency roofing services in Stow On The Wold Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Stow On The Wold Gloucestershire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInStowOnTheWoldGloucestershire;
