import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInIffleyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Iffley Oxfordshire"
      description="Voice-optimized emergency roofing services in Iffley Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Iffley Oxfordshire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInIffleyOxfordshire;
