import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInSloughBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Slough Berkshire"
      description="Voice-optimized emergency roofing services in Slough Berkshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Slough Berkshire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInSloughBerkshire;
