import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInChippingNortonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Chipping Norton Oxfordshire"
      description="Voice-optimized emergency roofing services in Chipping Norton Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Chipping Norton Oxfordshire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInChippingNortonOxfordshire;
