import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceEmergencyRoofingInReadingBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Emergency Roofing in Reading Berkshire"
      description="Voice-optimized emergency roofing services in Reading Berkshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Reading Berkshire"
      service="Emergency Roofing"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceEmergencyRoofingInReadingBerkshire;
