import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInDorkingSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Dorking Surrey"
      description="Voice-optimized gutter services services in Dorking Surrey. Use voice commands to get information, request quotes, and schedule appointments."
      location="Dorking Surrey"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInDorkingSurrey;
