import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInCheltenhamGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Cheltenham Gloucestershire"
      description="Voice-optimized gutter services services in Cheltenham Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Cheltenham Gloucestershire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInCheltenhamGloucestershire;
