import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInStowOnTheWoldGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Stow On The Wold Gloucestershire"
      description="Voice-optimized gutter services services in Stow On The Wold Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Stow On The Wold Gloucestershire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInStowOnTheWoldGloucestershire;
