import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInSummertownOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Summertown Oxfordshire"
      description="Voice-optimized gutter services services in Summertown Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Summertown Oxfordshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInSummertownOxfordshire;
