import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInBlackbirdLeysOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Blackbird Leys Oxfordshire"
      description="Voice-optimized gutter services services in Blackbird Leys Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Blackbird Leys Oxfordshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInBlackbirdLeysOxfordshire;
