import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInReadingBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Reading Berkshire"
      description="Voice-optimized gutter services services in Reading Berkshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Reading Berkshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInReadingBerkshire;
