import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInWindsorBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Windsor Berkshire"
      description="Voice-optimized gutter services services in Windsor Berkshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Windsor Berkshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInWindsorBerkshire;
