import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInBasingstokeHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Basingstoke Hampshire"
      description="Voice-optimized gutter services services in Basingstoke Hampshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Basingstoke Hampshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInBasingstokeHampshire;
