import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInPetersfieldHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Petersfield Hampshire"
      description="Voice-optimized gutter services services in Petersfield Hampshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Petersfield Hampshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInPetersfieldHampshire;
