import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInTewkesburyGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Tewkesbury Gloucestershire"
      description="Voice-optimized gutter services services in Tewkesbury Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Tewkesbury Gloucestershire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInTewkesburyGloucestershire;
