import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInWokinghamBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Wokingham Berkshire"
      description="Voice-optimized gutter services services in Wokingham Berkshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Wokingham Berkshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInWokinghamBerkshire;
