import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInReigateSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Reigate Surrey"
      description="Voice-optimized gutter services services in Reigate Surrey. Use voice commands to get information, request quotes, and schedule appointments."
      location="Reigate Surrey"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInReigateSurrey;
