import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInMidhurstWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Midhurst West Sussex"
      description="Voice-optimized gutter services services in Midhurst West Sussex. Use voice commands to get information, request quotes, and schedule appointments."
      location="Midhurst West Sussex"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInMidhurstWestSussex;
