import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInMoretonInMarshGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Moreton In Marsh Gloucestershire"
      description="Voice-optimized gutter services services in Moreton In Marsh Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Moreton In Marsh Gloucestershire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInMoretonInMarshGloucestershire;
