import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInLeatherheadSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Leatherhead Surrey"
      description="Voice-optimized gutter services services in Leatherhead Surrey. Use voice commands to get information, request quotes, and schedule appointments."
      location="Leatherhead Surrey"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInLeatherheadSurrey;
