import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInBerkeleyGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Berkeley Gloucestershire"
      description="Voice-optimized gutter services services in Berkeley Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Berkeley Gloucestershire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInBerkeleyGloucestershire;
