import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInWinslowBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Winslow Buckinghamshire"
      description="Voice-optimized gutter services services in Winslow Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Winslow Buckinghamshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInWinslowBuckinghamshire;
