import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInCranleighSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Cranleigh Surrey"
      description="Voice-optimized gutter services services in Cranleigh Surrey. Use voice commands to get information, request quotes, and schedule appointments."
      location="Cranleigh Surrey"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInCranleighSurrey;
