import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInMiltonKeynesBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Milton Keynes Buckinghamshire"
      description="Voice-optimized gutter services services in Milton Keynes Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Milton Keynes Buckinghamshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInMiltonKeynesBuckinghamshire;
