import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInAmesburyWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Amesbury Wiltshire"
      description="Voice-optimized gutter services services in Amesbury Wiltshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Amesbury Wiltshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInAmesburyWiltshire;
