import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInRedhillSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Redhill Surrey"
      description="Voice-optimized gutter services services in Redhill Surrey. Use voice commands to get information, request quotes, and schedule appointments."
      location="Redhill Surrey"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInRedhillSurrey;
