import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInAmershamBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Amersham Buckinghamshire"
      description="Voice-optimized gutter services services in Amersham Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Amersham Buckinghamshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInAmershamBuckinghamshire;
