import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInHenleyOnThamesOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Henley On Thames Oxfordshire"
      description="Voice-optimized gutter services services in Henley On Thames Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Henley On Thames Oxfordshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInHenleyOnThamesOxfordshire;
