import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInFarehamHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Fareham Hampshire"
      description="Voice-optimized gutter services services in Fareham Hampshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Fareham Hampshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInFarehamHampshire;
