import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInNailsworthGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Nailsworth Gloucestershire"
      description="Voice-optimized gutter services services in Nailsworth Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Nailsworth Gloucestershire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInNailsworthGloucestershire;
