import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInCalneWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Calne Wiltshire"
      description="Voice-optimized gutter services services in Calne Wiltshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Calne Wiltshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInCalneWiltshire;
