import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInMalmesburyWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Malmesbury Wiltshire"
      description="Voice-optimized gutter services services in Malmesbury Wiltshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Malmesbury Wiltshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInMalmesburyWiltshire;
