import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInChippingNortonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Chipping Norton Oxfordshire"
      description="Voice-optimized gutter services services in Chipping Norton Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Chipping Norton Oxfordshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInChippingNortonOxfordshire;
