import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInBotleyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Botley Oxfordshire"
      description="Voice-optimized gutter services services in Botley Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Botley Oxfordshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInBotleyOxfordshire;
