import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInGerrardsCrossBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Gerrards Cross Buckinghamshire"
      description="Voice-optimized gutter services services in Gerrards Cross Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Gerrards Cross Buckinghamshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInGerrardsCrossBuckinghamshire;
