import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInChalfontStPeterBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Chalfont St Peter Buckinghamshire"
      description="Voice-optimized gutter services services in Chalfont St Peter Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Chalfont St Peter Buckinghamshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInChalfontStPeterBuckinghamshire;
