import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInWottonUnderEdgeGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Wotton Under Edge Gloucestershire"
      description="Voice-optimized gutter services services in Wotton Under Edge Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Wotton Under Edge Gloucestershire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInWottonUnderEdgeGloucestershire;
