import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInSalisburyWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Salisbury Wiltshire"
      description="Voice-optimized gutter services services in Salisbury Wiltshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Salisbury Wiltshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInSalisburyWiltshire;
