import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInCamberleySurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Camberley Surrey"
      description="Voice-optimized gutter services services in Camberley Surrey. Use voice commands to get information, request quotes, and schedule appointments."
      location="Camberley Surrey"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInCamberleySurrey;
