import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInChichesterWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Chichester West Sussex"
      description="Voice-optimized gutter services services in Chichester West Sussex. Use voice commands to get information, request quotes, and schedule appointments."
      location="Chichester West Sussex"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInChichesterWestSussex;
