import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInCheshamBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Chesham Buckinghamshire"
      description="Voice-optimized gutter services services in Chesham Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Chesham Buckinghamshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInCheshamBuckinghamshire;
