import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInWendoverBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Wendover Buckinghamshire"
      description="Voice-optimized gutter services services in Wendover Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Wendover Buckinghamshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInWendoverBuckinghamshire;
