import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInGloucesterGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Gloucester Gloucestershire"
      description="Voice-optimized gutter services services in Gloucester Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Gloucester Gloucestershire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInGloucesterGloucestershire;
