import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInBuckinghamBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Buckingham Buckinghamshire"
      description="Voice-optimized gutter services services in Buckingham Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Buckingham Buckinghamshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInBuckinghamBuckinghamshire;
