import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInWolvercoteOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Wolvercote Oxfordshire"
      description="Voice-optimized gutter services services in Wolvercote Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Wolvercote Oxfordshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInWolvercoteOxfordshire;
