import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInTetburyGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Tetbury Gloucestershire"
      description="Voice-optimized gutter services services in Tetbury Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Tetbury Gloucestershire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInTetburyGloucestershire;
