import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInSouthamptonHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Southampton Hampshire"
      description="Voice-optimized gutter services services in Southampton Hampshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Southampton Hampshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInSouthamptonHampshire;
