import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInStonehouseGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Stonehouse Gloucestershire"
      description="Voice-optimized gutter services services in Stonehouse Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Stonehouse Gloucestershire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInStonehouseGloucestershire;
