import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInGreatMissendenBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Great Missenden Buckinghamshire"
      description="Voice-optimized gutter services services in Great Missenden Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Great Missenden Buckinghamshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInGreatMissendenBuckinghamshire;
