import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInWoodstockOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Woodstock Oxfordshire"
      description="Voice-optimized gutter services services in Woodstock Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Woodstock Oxfordshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInWoodstockOxfordshire;
