import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInAndoverHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Andover Hampshire"
      description="Voice-optimized gutter services services in Andover Hampshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Andover Hampshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInAndoverHampshire;
