import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInMarlowBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Marlow Buckinghamshire"
      description="Voice-optimized gutter services services in Marlow Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Marlow Buckinghamshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInMarlowBuckinghamshire;
