import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInChippingCampdenGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Chipping Campden Gloucestershire"
      description="Voice-optimized gutter services services in Chipping Campden Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Chipping Campden Gloucestershire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInChippingCampdenGloucestershire;
