import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInRoseHillOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Rose Hill Oxfordshire"
      description="Voice-optimized gutter services services in Rose Hill Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Rose Hill Oxfordshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInRoseHillOxfordshire;
