import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInBradfordOnAvonWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Bradford On Avon Wiltshire"
      description="Voice-optimized gutter services services in Bradford On Avon Wiltshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Bradford On Avon Wiltshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInBradfordOnAvonWiltshire;
