import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInCowleyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Cowley Oxfordshire"
      description="Voice-optimized gutter services services in Cowley Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Cowley Oxfordshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInCowleyOxfordshire;
