import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInLechladeGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Lechlade Gloucestershire"
      description="Voice-optimized gutter services services in Lechlade Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Lechlade Gloucestershire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInLechladeGloucestershire;
