import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInStonyStratfordBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Stony Stratford Buckinghamshire"
      description="Voice-optimized gutter services services in Stony Stratford Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Stony Stratford Buckinghamshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInStonyStratfordBuckinghamshire;
