import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInNewportPagnellBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Newport Pagnell Buckinghamshire"
      description="Voice-optimized gutter services services in Newport Pagnell Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Newport Pagnell Buckinghamshire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInNewportPagnellBuckinghamshire;
