import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInStroudGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Stroud Gloucestershire"
      description="Voice-optimized gutter services services in Stroud Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Stroud Gloucestershire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInStroudGloucestershire;
