import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceGutterServicesInFairfordGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Gutter Services in Fairford Gloucestershire"
      description="Voice-optimized gutter services services in Fairford Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Fairford Gloucestershire"
      service="Gutter Services"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceGutterServicesInFairfordGloucestershire;
