import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInSouthamptonHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Southampton Hampshire"
      description="Voice-optimized roof inspection services in Southampton Hampshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Southampton Hampshire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInSouthamptonHampshire;
