import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInMalmesburyWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Malmesbury Wiltshire"
      description="Voice-optimized roof maintenance services in Malmesbury Wiltshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Malmesbury Wiltshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInMalmesburyWiltshire;
