import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInWinchcombeGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Winchcombe Gloucestershire"
      description="Voice-optimized roof installation services in Winchcombe Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Winchcombe Gloucestershire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInWinchcombeGloucestershire;
