import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInStowOnTheWoldGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Stow On The Wold Gloucestershire"
      description="Voice-optimized roof installation services in Stow On The Wold Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Stow On The Wold Gloucestershire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInStowOnTheWoldGloucestershire;
