import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInThameOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Thame Oxfordshire"
      description="Voice-optimized roof inspection services in Thame Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Thame Oxfordshire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInThameOxfordshire;
