import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInAylesburyBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Aylesbury Buckinghamshire"
      description="Voice-optimized roof installation services in Aylesbury Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Aylesbury Buckinghamshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInAylesburyBuckinghamshire;
