import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInWantageOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Wantage Oxfordshire"
      description="Voice-optimized roof installation services in Wantage Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Wantage Oxfordshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInWantageOxfordshire;
