import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceLittlehamptonWestSussex: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Littlehampton West Sussex"
      description="Voice-optimized roofing services in Littlehampton West Sussex. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Littlehampton West Sussex"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceLittlehamptonWestSussex;
