import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceReigateSurrey: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Reigate Surrey"
      description="Voice-optimized roofing services in Reigate Surrey. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Reigate Surrey"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceReigateSurrey;
