import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceBlackbirdLeysOxfordshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Blackbird Leys Oxfordshire"
      description="Voice-optimized roofing services in Blackbird Leys Oxfordshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Blackbird Leys Oxfordshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceBlackbirdLeysOxfordshire;
