import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInEghamSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Egham Surrey"
      description="Voice-optimized roof maintenance services in Egham Surrey. Use voice commands to get information, request quotes, and schedule appointments."
      location="Egham Surrey"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInEghamSurrey;
