import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceTewkesburyGloucestershire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Tewkesbury Gloucestershire"
      description="Voice-optimized roofing services in Tewkesbury Gloucestershire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Tewkesbury Gloucestershire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceTewkesburyGloucestershire;
