import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceCheltenhamGloucestershire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Cheltenham Gloucestershire"
      description="Voice-optimized roofing services in Cheltenham Gloucestershire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Cheltenham Gloucestershire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceCheltenhamGloucestershire;
