import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceDorkingSurrey: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Dorking Surrey"
      description="Voice-optimized roofing services in Dorking Surrey. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Dorking Surrey"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceDorkingSurrey;
