import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInWindsorBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Windsor Berkshire"
      description="Voice-optimized roof inspection services in Windsor Berkshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Windsor Berkshire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInWindsorBerkshire;
