import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInSouthamptonHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Southampton Hampshire"
      description="Voice-optimized roof installation services in Southampton Hampshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Southampton Hampshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInSouthamptonHampshire;
