import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInEynshamOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Eynsham Oxfordshire"
      description="Voice-optimized roof inspection services in Eynsham Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Eynsham Oxfordshire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInEynshamOxfordshire;
