import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceCrawleyWestSussex: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Crawley West Sussex"
      description="Voice-optimized roofing services in Crawley West Sussex. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Crawley West Sussex"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceCrawleyWestSussex;
