import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInBerkeleyGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Berkeley Gloucestershire"
      description="Voice-optimized roof inspection services in Berkeley Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Berkeley Gloucestershire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInBerkeleyGloucestershire;
