import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceMoretonInMarshGloucestershire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Moreton In Marsh Gloucestershire"
      description="Voice-optimized roofing services in Moreton In Marsh Gloucestershire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Moreton In Marsh Gloucestershire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceMoretonInMarshGloucestershire;
