import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceDidcotOxfordshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Didcot Oxfordshire"
      description="Voice-optimized roofing services in Didcot Oxfordshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Didcot Oxfordshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceDidcotOxfordshire;
