import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInDursleyGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Dursley Gloucestershire"
      description="Voice-optimized roof installation services in Dursley Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Dursley Gloucestershire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInDursleyGloucestershire;
