import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInCheshamBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Chesham Buckinghamshire"
      description="Voice-optimized roof installation services in Chesham Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Chesham Buckinghamshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInCheshamBuckinghamshire;
