import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInGosportHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Gosport Hampshire"
      description="Voice-optimized roof inspection services in Gosport Hampshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Gosport Hampshire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInGosportHampshire;
