import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceHenleyOnThamesOxfordshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Henley On Thames Oxfordshire"
      description="Voice-optimized roofing services in Henley On Thames Oxfordshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Henley On Thames Oxfordshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceHenleyOnThamesOxfordshire;
