import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInHighWycombeBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in High Wycombe Buckinghamshire"
      description="Voice-optimized roof installation services in High Wycombe Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="High Wycombe Buckinghamshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInHighWycombeBuckinghamshire;
