import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInLymingtonHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Lymington Hampshire"
      description="Voice-optimized roof maintenance services in Lymington Hampshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Lymington Hampshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInLymingtonHampshire;
