import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceRoyalWoottonBassettWiltshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Royal Wootton Bassett Wiltshire"
      description="Voice-optimized roofing services in Royal Wootton Bassett Wiltshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Royal Wootton Bassett Wiltshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceRoyalWoottonBassettWiltshire;
