import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceGloucesterGloucestershire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Gloucester Gloucestershire"
      description="Voice-optimized roofing services in Gloucester Gloucestershire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Gloucester Gloucestershire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceGloucesterGloucestershire;
