import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInShorehamBySeaWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Shoreham By Sea West Sussex"
      description="Voice-optimized roof installation services in Shoreham By Sea West Sussex. Use voice commands to get information, request quotes, and schedule appointments."
      location="Shoreham By Sea West Sussex"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInShorehamBySeaWestSussex;
