import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInNewburyBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Newbury Berkshire"
      description="Voice-optimized roof inspection services in Newbury Berkshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Newbury Berkshire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInNewburyBerkshire;
