import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceWinchcombeGloucestershire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Winchcombe Gloucestershire"
      description="Voice-optimized roofing services in Winchcombe Gloucestershire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Winchcombe Gloucestershire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceWinchcombeGloucestershire;
