import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInGreatMissendenBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Great Missenden Buckinghamshire"
      description="Voice-optimized roof installation services in Great Missenden Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Great Missenden Buckinghamshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInGreatMissendenBuckinghamshire;
