import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceCirencesterGloucestershire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Cirencester Gloucestershire"
      description="Voice-optimized roofing services in Cirencester Gloucestershire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Cirencester Gloucestershire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceCirencesterGloucestershire;
