import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceEpsomSurrey: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Epsom Surrey"
      description="Voice-optimized roofing services in Epsom Surrey. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Epsom Surrey"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceEpsomSurrey;
