import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceBansteadSurrey: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Banstead Surrey"
      description="Voice-optimized roofing services in Banstead Surrey. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Banstead Surrey"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceBansteadSurrey;
