import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceChichesterWestSussex: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Chichester West Sussex"
      description="Voice-optimized roofing services in Chichester West Sussex. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Chichester West Sussex"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceChichesterWestSussex;
