import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInDidcotOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Didcot Oxfordshire"
      description="Voice-optimized roof maintenance services in Didcot Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Didcot Oxfordshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInDidcotOxfordshire;
