import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInOlneyBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Olney Buckinghamshire"
      description="Voice-optimized roof installation services in Olney Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Olney Buckinghamshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInOlneyBuckinghamshire;
