import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceTetburyGloucestershire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Tetbury Gloucestershire"
      description="Voice-optimized roofing services in Tetbury Gloucestershire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Tetbury Gloucestershire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceTetburyGloucestershire;
