import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInSloughBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Slough Berkshire"
      description="Voice-optimized roof installation services in Slough Berkshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Slough Berkshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInSloughBerkshire;
