import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceWoodstockOxfordshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Woodstock Oxfordshire"
      description="Voice-optimized roofing services in Woodstock Oxfordshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Woodstock Oxfordshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceWoodstockOxfordshire;
