import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceAldershotHampshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Aldershot Hampshire"
      description="Voice-optimized roofing services in Aldershot Hampshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Aldershot Hampshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceAldershotHampshire;
