import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInGerrardsCrossBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Gerrards Cross Buckinghamshire"
      description="Voice-optimized roof installation services in Gerrards Cross Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Gerrards Cross Buckinghamshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInGerrardsCrossBuckinghamshire;
