import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceChippingCampdenGloucestershire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Chipping Campden Gloucestershire"
      description="Voice-optimized roofing services in Chipping Campden Gloucestershire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Chipping Campden Gloucestershire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceChippingCampdenGloucestershire;
