import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceChalfontStPeterBuckinghamshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Chalfont St Peter Buckinghamshire"
      description="Voice-optimized roofing services in Chalfont St Peter Buckinghamshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Chalfont St Peter Buckinghamshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceChalfontStPeterBuckinghamshire;
