import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInReadingBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Reading Berkshire"
      description="Voice-optimized roof installation services in Reading Berkshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Reading Berkshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInReadingBerkshire;
