import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceFarehamHampshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Fareham Hampshire"
      description="Voice-optimized roofing services in Fareham Hampshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Fareham Hampshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceFarehamHampshire;
