import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInWallingfordOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Wallingford Oxfordshire"
      description="Voice-optimized roof installation services in Wallingford Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Wallingford Oxfordshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInWallingfordOxfordshire;
