import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInWendoverBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Wendover Buckinghamshire"
      description="Voice-optimized roof installation services in Wendover Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Wendover Buckinghamshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInWendoverBuckinghamshire;
