import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInFleetHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Fleet Hampshire"
      description="Voice-optimized roof inspection services in Fleet Hampshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Fleet Hampshire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInFleetHampshire;
