import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceDevizesWiltshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Devizes Wiltshire"
      description="Voice-optimized roofing services in Devizes Wiltshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Devizes Wiltshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceDevizesWiltshire;
