import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInSummertownOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Summertown Oxfordshire"
      description="Voice-optimized roof inspection services in Summertown Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Summertown Oxfordshire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInSummertownOxfordshire;
