import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceEastleighHampshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Eastleigh Hampshire"
      description="Voice-optimized roofing services in Eastleigh Hampshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Eastleigh Hampshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceEastleighHampshire;
