import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceGreatMissendenBuckinghamshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Great Missenden Buckinghamshire"
      description="Voice-optimized roofing services in Great Missenden Buckinghamshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Great Missenden Buckinghamshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceGreatMissendenBuckinghamshire;
