import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInRoyalWoottonBassettWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Royal Wootton Bassett Wiltshire"
      description="Voice-optimized roof installation services in Royal Wootton Bassett Wiltshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Royal Wootton Bassett Wiltshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInRoyalWoottonBassettWiltshire;
