import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInBracknellBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Bracknell Berkshire"
      description="Voice-optimized roof maintenance services in Bracknell Berkshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Bracknell Berkshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInBracknellBerkshire;
