import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceGosportHampshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Gosport Hampshire"
      description="Voice-optimized roofing services in Gosport Hampshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Gosport Hampshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceGosportHampshire;
