import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceWestburyWiltshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Westbury Wiltshire"
      description="Voice-optimized roofing services in Westbury Wiltshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Westbury Wiltshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceWestburyWiltshire;
