import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInIffleyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Iffley Oxfordshire"
      description="Voice-optimized roof installation services in Iffley Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Iffley Oxfordshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInIffleyOxfordshire;
