import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInOxfordOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Oxford Oxfordshire"
      description="Voice-optimized roof maintenance services in Oxford Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Oxford Oxfordshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInOxfordOxfordshire;
