import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInPrincesRisboroughBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Princes Risborough Buckinghamshire"
      description="Voice-optimized roof installation services in Princes Risborough Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Princes Risborough Buckinghamshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInPrincesRisboroughBuckinghamshire;
