import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceAmershamBuckinghamshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Amersham Buckinghamshire"
      description="Voice-optimized roofing services in Amersham Buckinghamshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Amersham Buckinghamshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceAmershamBuckinghamshire;
