import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceWottonUnderEdgeGloucestershire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Wotton Under Edge Gloucestershire"
      description="Voice-optimized roofing services in Wotton Under Edge Gloucestershire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Wotton Under Edge Gloucestershire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceWottonUnderEdgeGloucestershire;
