import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInGuildfordSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Guildford Surrey"
      description="Voice-optimized roof maintenance services in Guildford Surrey. Use voice commands to get information, request quotes, and schedule appointments."
      location="Guildford Surrey"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInGuildfordSurrey;
