import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceArundelWestSussex: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Arundel West Sussex"
      description="Voice-optimized roofing services in Arundel West Sussex. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Arundel West Sussex"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceArundelWestSussex;
