import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInCheltenhamGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Cheltenham Gloucestershire"
      description="Voice-optimized roof installation services in Cheltenham Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Cheltenham Gloucestershire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInCheltenhamGloucestershire;
