import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInWokinghamBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Wokingham Berkshire"
      description="Voice-optimized roof inspection services in Wokingham Berkshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Wokingham Berkshire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInWokinghamBerkshire;
