import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInMiltonKeynesBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Milton Keynes Buckinghamshire"
      description="Voice-optimized roof maintenance services in Milton Keynes Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Milton Keynes Buckinghamshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInMiltonKeynesBuckinghamshire;
