import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceBradfordOnAvonWiltshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Bradford On Avon Wiltshire"
      description="Voice-optimized roofing services in Bradford On Avon Wiltshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Bradford On Avon Wiltshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceBradfordOnAvonWiltshire;
