import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceLechladeGloucestershire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Lechlade Gloucestershire"
      description="Voice-optimized roofing services in Lechlade Gloucestershire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Lechlade Gloucestershire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceLechladeGloucestershire;
