import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInStainesSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Staines Surrey"
      description="Voice-optimized roof maintenance services in Staines Surrey. Use voice commands to get information, request quotes, and schedule appointments."
      location="Staines Surrey"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInStainesSurrey;
