import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceAbingdonOxfordshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Abingdon Oxfordshire"
      description="Voice-optimized roofing services in Abingdon Oxfordshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Abingdon Oxfordshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceAbingdonOxfordshire;
