import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInSouthamptonHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Southampton Hampshire"
      description="Voice-optimized roof maintenance services in Southampton Hampshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Southampton Hampshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInSouthamptonHampshire;
