import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInBansteadSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Banstead Surrey"
      description="Voice-optimized roof inspection services in Banstead Surrey. Use voice commands to get information, request quotes, and schedule appointments."
      location="Banstead Surrey"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInBansteadSurrey;
