import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInHenleyOnThamesOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Henley On Thames Oxfordshire"
      description="Voice-optimized roof maintenance services in Henley On Thames Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Henley On Thames Oxfordshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInHenleyOnThamesOxfordshire;
