import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceSelseyWestSussex: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Selsey West Sussex"
      description="Voice-optimized roofing services in Selsey West Sussex. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Selsey West Sussex"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceSelseyWestSussex;
