import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInTidworthWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Tidworth Wiltshire"
      description="Voice-optimized roof installation services in Tidworth Wiltshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Tidworth Wiltshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInTidworthWiltshire;
