import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInEsherSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Esher Surrey"
      description="Voice-optimized roof installation services in Esher Surrey. Use voice commands to get information, request quotes, and schedule appointments."
      location="Esher Surrey"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInEsherSurrey;
