import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInMiltonKeynesBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Milton Keynes Buckinghamshire"
      description="Voice-optimized roof installation services in Milton Keynes Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Milton Keynes Buckinghamshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInMiltonKeynesBuckinghamshire;
