import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceReadingBerkshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Reading Berkshire"
      description="Voice-optimized roofing services in Reading Berkshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Reading Berkshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceReadingBerkshire;
