import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceCalneWiltshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Calne Wiltshire"
      description="Voice-optimized roofing services in Calne Wiltshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Calne Wiltshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceCalneWiltshire;
