import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceDursleyGloucestershire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Dursley Gloucestershire"
      description="Voice-optimized roofing services in Dursley Gloucestershire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Dursley Gloucestershire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceDursleyGloucestershire;
