import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceJerichoOxfordshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Jericho Oxfordshire"
      description="Voice-optimized roofing services in Jericho Oxfordshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Jericho Oxfordshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceJerichoOxfordshire;
