import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceIffleyOxfordshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Iffley Oxfordshire"
      description="Voice-optimized roofing services in Iffley Oxfordshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Iffley Oxfordshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceIffleyOxfordshire;
