import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInCheshamBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Chesham Buckinghamshire"
      description="Voice-optimized roof maintenance services in Chesham Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Chesham Buckinghamshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInCheshamBuckinghamshire;
