import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInShorehamBySeaWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Shoreham By Sea West Sussex"
      description="Voice-optimized roof inspection services in Shoreham By Sea West Sussex. Use voice commands to get information, request quotes, and schedule appointments."
      location="Shoreham By Sea West Sussex"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInShorehamBySeaWestSussex;
