import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceSummertownOxfordshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Summertown Oxfordshire"
      description="Voice-optimized roofing services in Summertown Oxfordshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Summertown Oxfordshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceSummertownOxfordshire;
