import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInCranleighSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Cranleigh Surrey"
      description="Voice-optimized roof installation services in Cranleigh Surrey. Use voice commands to get information, request quotes, and schedule appointments."
      location="Cranleigh Surrey"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInCranleighSurrey;
