import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInRingwoodHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Ringwood Hampshire"
      description="Voice-optimized roof maintenance services in Ringwood Hampshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Ringwood Hampshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInRingwoodHampshire;
