import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInAbingdonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Abingdon Oxfordshire"
      description="Voice-optimized roof maintenance services in Abingdon Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Abingdon Oxfordshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInAbingdonOxfordshire;
