import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInChalfontStPeterBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Chalfont St Peter Buckinghamshire"
      description="Voice-optimized roof installation services in Chalfont St Peter Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Chalfont St Peter Buckinghamshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInChalfontStPeterBuckinghamshire;
