import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInHenleyOnThamesOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Henley On Thames Oxfordshire"
      description="Voice-optimized roof inspection services in Henley On Thames Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Henley On Thames Oxfordshire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInHenleyOnThamesOxfordshire;
