import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenance: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance"
      description="Voice-optimized roof maintenance services. Use voice commands to get information, request quotes, and schedule appointments."
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenance;
