import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInRustingtonWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Rustington West Sussex"
      description="Voice-optimized roof installation services in Rustington West Sussex. Use voice commands to get information, request quotes, and schedule appointments."
      location="Rustington West Sussex"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInRustingtonWestSussex;
