import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInWallingfordOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Wallingford Oxfordshire"
      description="Voice-optimized roof maintenance services in Wallingford Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Wallingford Oxfordshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInWallingfordOxfordshire;
