import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInSloughBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Slough Berkshire"
      description="Voice-optimized roof inspection services in Slough Berkshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Slough Berkshire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInSloughBerkshire;
