import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInLechladeGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Lechlade Gloucestershire"
      description="Voice-optimized roof maintenance services in Lechlade Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Lechlade Gloucestershire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInLechladeGloucestershire;
