import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInMaidenheadBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Maidenhead Berkshire"
      description="Voice-optimized roof inspection services in Maidenhead Berkshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Maidenhead Berkshire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInMaidenheadBerkshire;
