import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceSwindonWiltshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Swindon Wiltshire"
      description="Voice-optimized roofing services in Swindon Wiltshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Swindon Wiltshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceSwindonWiltshire;
