import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceFairfordGloucestershire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Fairford Gloucestershire"
      description="Voice-optimized roofing services in Fairford Gloucestershire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Fairford Gloucestershire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceFairfordGloucestershire;
