import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceHorleySurrey: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Horley Surrey"
      description="Voice-optimized roofing services in Horley Surrey. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Horley Surrey"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceHorleySurrey;
