import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInStowOnTheWoldGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Stow On The Wold Gloucestershire"
      description="Voice-optimized roof maintenance services in Stow On The Wold Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Stow On The Wold Gloucestershire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInStowOnTheWoldGloucestershire;
