import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInMaidenheadBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Maidenhead Berkshire"
      description="Voice-optimized roof installation services in Maidenhead Berkshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Maidenhead Berkshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInMaidenheadBerkshire;
