import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoicePetersfieldHampshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Petersfield Hampshire"
      description="Voice-optimized roofing services in Petersfield Hampshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Petersfield Hampshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoicePetersfieldHampshire;
