import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoicePortsmouthHampshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Portsmouth Hampshire"
      description="Voice-optimized roofing services in Portsmouth Hampshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Portsmouth Hampshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoicePortsmouthHampshire;
