import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceFarnboroughHampshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Farnborough Hampshire"
      description="Voice-optimized roofing services in Farnborough Hampshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Farnborough Hampshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceFarnboroughHampshire;
