import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInStonyStratfordBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Stony Stratford Buckinghamshire"
      description="Voice-optimized roof inspection services in Stony Stratford Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Stony Stratford Buckinghamshire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInStonyStratfordBuckinghamshire;
