import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInRoseHillOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Rose Hill Oxfordshire"
      description="Voice-optimized roof maintenance services in Rose Hill Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Rose Hill Oxfordshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInRoseHillOxfordshire;
