import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInWinchcombeGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Winchcombe Gloucestershire"
      description="Voice-optimized roof maintenance services in Winchcombe Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Winchcombe Gloucestershire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInWinchcombeGloucestershire;
