import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInDursleyGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Dursley Gloucestershire"
      description="Voice-optimized roof maintenance services in Dursley Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Dursley Gloucestershire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInDursleyGloucestershire;
