import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceSouthwickWestSussex: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Southwick West Sussex"
      description="Voice-optimized roofing services in Southwick West Sussex. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Southwick West Sussex"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceSouthwickWestSussex;
