import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceCheshamBuckinghamshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Chesham Buckinghamshire"
      description="Voice-optimized roofing services in Chesham Buckinghamshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Chesham Buckinghamshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceCheshamBuckinghamshire;
