import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInCorshamWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Corsham Wiltshire"
      description="Voice-optimized roof installation services in Corsham Wiltshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Corsham Wiltshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInCorshamWiltshire;
