import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceWatlingtonOxfordshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Watlington Oxfordshire"
      description="Voice-optimized roofing services in Watlington Oxfordshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Watlington Oxfordshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceWatlingtonOxfordshire;
