import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceFaringdonOxfordshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Faringdon Oxfordshire"
      description="Voice-optimized roofing services in Faringdon Oxfordshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Faringdon Oxfordshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceFaringdonOxfordshire;
