import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInHighWycombeBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in High Wycombe Buckinghamshire"
      description="Voice-optimized roof inspection services in High Wycombe Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="High Wycombe Buckinghamshire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInHighWycombeBuckinghamshire;
