import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceCartertonOxfordshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Carterton Oxfordshire"
      description="Voice-optimized roofing services in Carterton Oxfordshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Carterton Oxfordshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceCartertonOxfordshire;
