import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceRomseyHampshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Romsey Hampshire"
      description="Voice-optimized roofing services in Romsey Hampshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Romsey Hampshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceRomseyHampshire;
