import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceStroudGloucestershire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Stroud Gloucestershire"
      description="Voice-optimized roofing services in Stroud Gloucestershire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Stroud Gloucestershire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceStroudGloucestershire;
