import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceBanburyOxfordshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Banbury Oxfordshire"
      description="Voice-optimized roofing services in Banbury Oxfordshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Banbury Oxfordshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceBanburyOxfordshire;
