import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallation: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation"
      description="Voice-optimized roof installation services. Use voice commands to get information, request quotes, and schedule appointments."
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallation;
