import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceWallingfordOxfordshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Wallingford Oxfordshire"
      description="Voice-optimized roofing services in Wallingford Oxfordshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Wallingford Oxfordshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceWallingfordOxfordshire;
