import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceMarlboroughWiltshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Marlborough Wiltshire"
      description="Voice-optimized roofing services in Marlborough Wiltshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Marlborough Wiltshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceMarlboroughWiltshire;
