import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInMoretonInMarshGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Moreton In Marsh Gloucestershire"
      description="Voice-optimized roof inspection services in Moreton In Marsh Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Moreton In Marsh Gloucestershire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInMoretonInMarshGloucestershire;
