import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInCalneWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Calne Wiltshire"
      description="Voice-optimized roof inspection services in Calne Wiltshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Calne Wiltshire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInCalneWiltshire;
