import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInWantageOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Wantage Oxfordshire"
      description="Voice-optimized roof inspection services in Wantage Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Wantage Oxfordshire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInWantageOxfordshire;
