import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceBurgessHillWestSussex: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Burgess Hill West Sussex"
      description="Voice-optimized roofing services in Burgess Hill West Sussex. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Burgess Hill West Sussex"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceBurgessHillWestSussex;
