import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInAylesburyBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Aylesbury Buckinghamshire"
      description="Voice-optimized roof maintenance services in Aylesbury Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Aylesbury Buckinghamshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInAylesburyBuckinghamshire;
