import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceBracknellBerkshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Bracknell Berkshire"
      description="Voice-optimized roofing services in Bracknell Berkshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Bracknell Berkshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceBracknellBerkshire;
