import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInDevizesWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Devizes Wiltshire"
      description="Voice-optimized roof inspection services in Devizes Wiltshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Devizes Wiltshire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInDevizesWiltshire;
