import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInAmershamBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Amersham Buckinghamshire"
      description="Voice-optimized roof maintenance services in Amersham Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Amersham Buckinghamshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInAmershamBuckinghamshire;
