import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceChippingNortonOxfordshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Chipping Norton Oxfordshire"
      description="Voice-optimized roofing services in Chipping Norton Oxfordshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Chipping Norton Oxfordshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceChippingNortonOxfordshire;
