import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceAmesburyWiltshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Amesbury Wiltshire"
      description="Voice-optimized roofing services in Amesbury Wiltshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Amesbury Wiltshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceAmesburyWiltshire;
