import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInFairfordGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Fairford Gloucestershire"
      description="Voice-optimized roof maintenance services in Fairford Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Fairford Gloucestershire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInFairfordGloucestershire;
