import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInWoodstockOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Woodstock Oxfordshire"
      description="Voice-optimized roof inspection services in Woodstock Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Woodstock Oxfordshire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInWoodstockOxfordshire;
