import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInStonehouseGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Stonehouse Gloucestershire"
      description="Voice-optimized roof maintenance services in Stonehouse Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Stonehouse Gloucestershire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInStonehouseGloucestershire;
