import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInMidhurstWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Midhurst West Sussex"
      description="Voice-optimized roof installation services in Midhurst West Sussex. Use voice commands to get information, request quotes, and schedule appointments."
      location="Midhurst West Sussex"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInMidhurstWestSussex;
