import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceSalisburyWiltshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Salisbury Wiltshire"
      description="Voice-optimized roofing services in Salisbury Wiltshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Salisbury Wiltshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceSalisburyWiltshire;
