import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceStainesSurrey: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Staines Surrey"
      description="Voice-optimized roofing services in Staines Surrey. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Staines Surrey"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceStainesSurrey;
