import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInChippingNortonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Chipping Norton Oxfordshire"
      description="Voice-optimized roof maintenance services in Chipping Norton Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Chipping Norton Oxfordshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInChippingNortonOxfordshire;
