import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInAndoverHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Andover Hampshire"
      description="Voice-optimized roof installation services in Andover Hampshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Andover Hampshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInAndoverHampshire;
