import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInHavantHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Havant Hampshire"
      description="Voice-optimized roof inspection services in Havant Hampshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Havant Hampshire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInHavantHampshire;
