import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInMarlboroughWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Marlborough Wiltshire"
      description="Voice-optimized roof inspection services in Marlborough Wiltshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Marlborough Wiltshire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInMarlboroughWiltshire;
