import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInAmershamBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Amersham Buckinghamshire"
      description="Voice-optimized roof inspection services in Amersham Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Amersham Buckinghamshire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInAmershamBuckinghamshire;
