import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInStroudGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Stroud Gloucestershire"
      description="Voice-optimized roof installation services in Stroud Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Stroud Gloucestershire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInStroudGloucestershire;
