import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInBanburyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Banbury Oxfordshire"
      description="Voice-optimized roof installation services in Banbury Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Banbury Oxfordshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInBanburyOxfordshire;
