import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceCrickladeWiltshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Cricklade Wiltshire"
      description="Voice-optimized roofing services in Cricklade Wiltshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Cricklade Wiltshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceCrickladeWiltshire;
