import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInRoseHillOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Rose Hill Oxfordshire"
      description="Voice-optimized roof inspection services in Rose Hill Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Rose Hill Oxfordshire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInRoseHillOxfordshire;
