import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceHeadingtonOxfordshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Headington Oxfordshire"
      description="Voice-optimized roofing services in Headington Oxfordshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Headington Oxfordshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceHeadingtonOxfordshire;
