import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInBerkeleyGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Berkeley Gloucestershire"
      description="Voice-optimized roof maintenance services in Berkeley Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Berkeley Gloucestershire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInBerkeleyGloucestershire;
