import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInChalfontStPeterBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Chalfont St Peter Buckinghamshire"
      description="Voice-optimized roof inspection services in Chalfont St Peter Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Chalfont St Peter Buckinghamshire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInChalfontStPeterBuckinghamshire;
