import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInGosportHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Gosport Hampshire"
      description="Voice-optimized roof maintenance services in Gosport Hampshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Gosport Hampshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInGosportHampshire;
