import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInWottonUnderEdgeGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Wotton Under Edge Gloucestershire"
      description="Voice-optimized roof maintenance services in Wotton Under Edge Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Wotton Under Edge Gloucestershire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInWottonUnderEdgeGloucestershire;
