import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInMarlowBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Marlow Buckinghamshire"
      description="Voice-optimized roof inspection services in Marlow Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Marlow Buckinghamshire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInMarlowBuckinghamshire;
