import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInPewseyWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Pewsey Wiltshire"
      description="Voice-optimized roof installation services in Pewsey Wiltshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Pewsey Wiltshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInPewseyWiltshire;
