import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInCrawleyWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Crawley West Sussex"
      description="Voice-optimized roof installation services in Crawley West Sussex. Use voice commands to get information, request quotes, and schedule appointments."
      location="Crawley West Sussex"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInCrawleyWestSussex;
