import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceNailsworthGloucestershire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Nailsworth Gloucestershire"
      description="Voice-optimized roofing services in Nailsworth Gloucestershire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Nailsworth Gloucestershire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceNailsworthGloucestershire;
