import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceFarnhamSurrey: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Farnham Surrey"
      description="Voice-optimized roofing services in Farnham Surrey. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Farnham Surrey"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceFarnhamSurrey;
