import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInOxfordOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Oxford Oxfordshire"
      description="Voice-optimized roof inspection services in Oxford Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Oxford Oxfordshire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInOxfordOxfordshire;
