import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInBradfordOnAvonWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Bradford On Avon Wiltshire"
      description="Voice-optimized roof installation services in Bradford On Avon Wiltshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Bradford On Avon Wiltshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInBradfordOnAvonWiltshire;
