import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInChippingCampdenGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Chipping Campden Gloucestershire"
      description="Voice-optimized roof installation services in Chipping Campden Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Chipping Campden Gloucestershire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInChippingCampdenGloucestershire;
