import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceSteyningWestSussex: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Steyning West Sussex"
      description="Voice-optimized roofing services in Steyning West Sussex. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Steyning West Sussex"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceSteyningWestSussex;
