import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInFarnhamSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Farnham Surrey"
      description="Voice-optimized roof installation services in Farnham Surrey. Use voice commands to get information, request quotes, and schedule appointments."
      location="Farnham Surrey"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInFarnhamSurrey;
