import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceEghamSurrey: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Egham Surrey"
      description="Voice-optimized roofing services in Egham Surrey. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Egham Surrey"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceEghamSurrey;
