import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceSloughBerkshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Slough Berkshire"
      description="Voice-optimized roofing services in Slough Berkshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Slough Berkshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceSloughBerkshire;
