import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInHaslemereSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Haslemere Surrey"
      description="Voice-optimized roof maintenance services in Haslemere Surrey. Use voice commands to get information, request quotes, and schedule appointments."
      location="Haslemere Surrey"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInHaslemereSurrey;
