import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInStowOnTheWoldGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Stow On The Wold Gloucestershire"
      description="Voice-optimized roof inspection services in Stow On The Wold Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Stow On The Wold Gloucestershire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInStowOnTheWoldGloucestershire;
