import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoicePetworthWestSussex: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Petworth West Sussex"
      description="Voice-optimized roofing services in Petworth West Sussex. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Petworth West Sussex"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoicePetworthWestSussex;
