import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceWindsorBerkshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Windsor Berkshire"
      description="Voice-optimized roofing services in Windsor Berkshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Windsor Berkshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceWindsorBerkshire;
