import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceHenfieldWestSussex: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Henfield West Sussex"
      description="Voice-optimized roofing services in Henfield West Sussex. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Henfield West Sussex"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceHenfieldWestSussex;
