import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInLittlehamptonWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Littlehampton West Sussex"
      description="Voice-optimized roof inspection services in Littlehampton West Sussex. Use voice commands to get information, request quotes, and schedule appointments."
      location="Littlehampton West Sussex"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInLittlehamptonWestSussex;
