import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInNewburyBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Newbury Berkshire"
      description="Voice-optimized roof maintenance services in Newbury Berkshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Newbury Berkshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInNewburyBerkshire;
