import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceCharlburyOxfordshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Charlbury Oxfordshire"
      description="Voice-optimized roofing services in Charlbury Oxfordshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Charlbury Oxfordshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceCharlburyOxfordshire;
