import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInTewkesburyGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Tewkesbury Gloucestershire"
      description="Voice-optimized roof installation services in Tewkesbury Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Tewkesbury Gloucestershire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInTewkesburyGloucestershire;
