import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInCranleighSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Cranleigh Surrey"
      description="Voice-optimized roof maintenance services in Cranleigh Surrey. Use voice commands to get information, request quotes, and schedule appointments."
      location="Cranleigh Surrey"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInCranleighSurrey;
