import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceCorshamWiltshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Corsham Wiltshire"
      description="Voice-optimized roofing services in Corsham Wiltshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Corsham Wiltshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceCorshamWiltshire;
