import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceAltonHampshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Alton Hampshire"
      description="Voice-optimized roofing services in Alton Hampshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Alton Hampshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceAltonHampshire;
