import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceWokingSurrey: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Woking Surrey"
      description="Voice-optimized roofing services in Woking Surrey. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Woking Surrey"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceWokingSurrey;
