import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInNewburyBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Newbury Berkshire"
      description="Voice-optimized roof installation services in Newbury Berkshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Newbury Berkshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInNewburyBerkshire;
