import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceWantageOxfordshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Wantage Oxfordshire"
      description="Voice-optimized roofing services in Wantage Oxfordshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Wantage Oxfordshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceWantageOxfordshire;
