import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInChippenhamWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Chippenham Wiltshire"
      description="Voice-optimized roof maintenance services in Chippenham Wiltshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Chippenham Wiltshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInChippenhamWiltshire;
