import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceWarminsterWiltshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Warminster Wiltshire"
      description="Voice-optimized roofing services in Warminster Wiltshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Warminster Wiltshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceWarminsterWiltshire;
