import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInCharlburyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Charlbury Oxfordshire"
      description="Voice-optimized roof maintenance services in Charlbury Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Charlbury Oxfordshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInCharlburyOxfordshire;
