import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceTottonHampshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Totton Hampshire"
      description="Voice-optimized roofing services in Totton Hampshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Totton Hampshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceTottonHampshire;
