import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInReigateSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Reigate Surrey"
      description="Voice-optimized roof inspection services in Reigate Surrey. Use voice commands to get information, request quotes, and schedule appointments."
      location="Reigate Surrey"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInReigateSurrey;
