import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceNewburyBerkshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Newbury Berkshire"
      description="Voice-optimized roofing services in Newbury Berkshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Newbury Berkshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceNewburyBerkshire;
