import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInNewportPagnellBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Newport Pagnell Buckinghamshire"
      description="Voice-optimized roof inspection services in Newport Pagnell Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Newport Pagnell Buckinghamshire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInNewportPagnellBuckinghamshire;
