import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInAldershotHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Aldershot Hampshire"
      description="Voice-optimized roof inspection services in Aldershot Hampshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Aldershot Hampshire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInAldershotHampshire;
