import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceWiltonWiltshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Wilton Wiltshire"
      description="Voice-optimized roofing services in Wilton Wiltshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Wilton Wiltshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceWiltonWiltshire;
