import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceHaywardsHeathWestSussex: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Haywards Heath West Sussex"
      description="Voice-optimized roofing services in Haywards Heath West Sussex. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Haywards Heath West Sussex"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceHaywardsHeathWestSussex;
