import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceBicesterOxfordshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Bicester Oxfordshire"
      description="Voice-optimized roofing services in Bicester Oxfordshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Bicester Oxfordshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceBicesterOxfordshire;
