import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInMarlowBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Marlow Buckinghamshire"
      description="Voice-optimized roof maintenance services in Marlow Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Marlow Buckinghamshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInMarlowBuckinghamshire;
