import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInGodalmingSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Godalming Surrey"
      description="Voice-optimized roof installation services in Godalming Surrey. Use voice commands to get information, request quotes, and schedule appointments."
      location="Godalming Surrey"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInGodalmingSurrey;
