import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInWatlingtonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Watlington Oxfordshire"
      description="Voice-optimized roof maintenance services in Watlington Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Watlington Oxfordshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInWatlingtonOxfordshire;
