import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceStowOnTheWoldGloucestershire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Stow On The Wold Gloucestershire"
      description="Voice-optimized roofing services in Stow On The Wold Gloucestershire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Stow On The Wold Gloucestershire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceStowOnTheWoldGloucestershire;
