import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInBerkeleyGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Berkeley Gloucestershire"
      description="Voice-optimized roof installation services in Berkeley Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Berkeley Gloucestershire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInBerkeleyGloucestershire;
