import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceEynshamOxfordshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Eynsham Oxfordshire"
      description="Voice-optimized roofing services in Eynsham Oxfordshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Eynsham Oxfordshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceEynshamOxfordshire;
