import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInStroudGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Stroud Gloucestershire"
      description="Voice-optimized roof maintenance services in Stroud Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Stroud Gloucestershire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInStroudGloucestershire;
