import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceEsherSurrey: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Esher Surrey"
      description="Voice-optimized roofing services in Esher Surrey. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Esher Surrey"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceEsherSurrey;
