import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceWinslowBuckinghamshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Winslow Buckinghamshire"
      description="Voice-optimized roofing services in Winslow Buckinghamshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Winslow Buckinghamshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceWinslowBuckinghamshire;
