import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceHighWycombeBuckinghamshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in High Wycombe Buckinghamshire"
      description="Voice-optimized roofing services in High Wycombe Buckinghamshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="High Wycombe Buckinghamshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceHighWycombeBuckinghamshire;
