import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceTrowbridgeWiltshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Trowbridge Wiltshire"
      description="Voice-optimized roofing services in Trowbridge Wiltshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Trowbridge Wiltshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceTrowbridgeWiltshire;
