import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInBurnhamBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Burnham Buckinghamshire"
      description="Voice-optimized roof installation services in Burnham Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Burnham Buckinghamshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInBurnhamBuckinghamshire;
