import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInWatlingtonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Watlington Oxfordshire"
      description="Voice-optimized roof installation services in Watlington Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Watlington Oxfordshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInWatlingtonOxfordshire;
