import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInRedhillSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Redhill Surrey"
      description="Voice-optimized roof maintenance services in Redhill Surrey. Use voice commands to get information, request quotes, and schedule appointments."
      location="Redhill Surrey"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInRedhillSurrey;
