import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInGodalmingSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Godalming Surrey"
      description="Voice-optimized roof inspection services in Godalming Surrey. Use voice commands to get information, request quotes, and schedule appointments."
      location="Godalming Surrey"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInGodalmingSurrey;
