import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInTewkesburyGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Tewkesbury Gloucestershire"
      description="Voice-optimized roof inspection services in Tewkesbury Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Tewkesbury Gloucestershire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInTewkesburyGloucestershire;
