import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInMoretonInMarshGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Moreton In Marsh Gloucestershire"
      description="Voice-optimized roof installation services in Moreton In Marsh Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Moreton In Marsh Gloucestershire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInMoretonInMarshGloucestershire;
