import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInWokinghamBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Wokingham Berkshire"
      description="Voice-optimized roof installation services in Wokingham Berkshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Wokingham Berkshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInWokinghamBerkshire;
