import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceStonyStratfordBuckinghamshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Stony Stratford Buckinghamshire"
      description="Voice-optimized roofing services in Stony Stratford Buckinghamshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Stony Stratford Buckinghamshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceStonyStratfordBuckinghamshire;
