import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInSloughBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Slough Berkshire"
      description="Voice-optimized roof maintenance services in Slough Berkshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Slough Berkshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInSloughBerkshire;
