import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceMarstonOxfordshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Marston Oxfordshire"
      description="Voice-optimized roofing services in Marston Oxfordshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Marston Oxfordshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceMarstonOxfordshire;
