import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceGuildfordSurrey: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Guildford Surrey"
      description="Voice-optimized roofing services in Guildford Surrey. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Guildford Surrey"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceGuildfordSurrey;
