import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInBanburyOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Banbury Oxfordshire"
      description="Voice-optimized roof inspection services in Banbury Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Banbury Oxfordshire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInBanburyOxfordshire;
