import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInEynshamOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Eynsham Oxfordshire"
      description="Voice-optimized roof maintenance services in Eynsham Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Eynsham Oxfordshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInEynshamOxfordshire;
