import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceWeybridgeSurrey: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Weybridge Surrey"
      description="Voice-optimized roofing services in Weybridge Surrey. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Weybridge Surrey"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceWeybridgeSurrey;
