import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceWinchesterHampshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Winchester Hampshire"
      description="Voice-optimized roofing services in Winchester Hampshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Winchester Hampshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceWinchesterHampshire;
