import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceWorthingWestSussex: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Worthing West Sussex"
      description="Voice-optimized roofing services in Worthing West Sussex. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Worthing West Sussex"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceWorthingWestSussex;
