import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceMalmesburyWiltshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Malmesbury Wiltshire"
      description="Voice-optimized roofing services in Malmesbury Wiltshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Malmesbury Wiltshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceMalmesburyWiltshire;
