import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInChippingCampdenGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Chipping Campden Gloucestershire"
      description="Voice-optimized roof inspection services in Chipping Campden Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Chipping Campden Gloucestershire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInChippingCampdenGloucestershire;
