import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInGreatMissendenBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Great Missenden Buckinghamshire"
      description="Voice-optimized roof maintenance services in Great Missenden Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Great Missenden Buckinghamshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInGreatMissendenBuckinghamshire;
