import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoicePewseyWiltshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Pewsey Wiltshire"
      description="Voice-optimized roofing services in Pewsey Wiltshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Pewsey Wiltshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoicePewseyWiltshire;
