import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInWindsorBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Windsor Berkshire"
      description="Voice-optimized roof maintenance services in Windsor Berkshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Windsor Berkshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInWindsorBerkshire;
