import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceBurnhamBuckinghamshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Burnham Buckinghamshire"
      description="Voice-optimized roofing services in Burnham Buckinghamshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Burnham Buckinghamshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceBurnhamBuckinghamshire;
