import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInWatlingtonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Watlington Oxfordshire"
      description="Voice-optimized roof inspection services in Watlington Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Watlington Oxfordshire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInWatlingtonOxfordshire;
