import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceLymingtonHampshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Lymington Hampshire"
      description="Voice-optimized roofing services in Lymington Hampshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Lymington Hampshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceLymingtonHampshire;
