import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceThameOxfordshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Thame Oxfordshire"
      description="Voice-optimized roofing services in Thame Oxfordshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Thame Oxfordshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceThameOxfordshire;
