import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceKidlingtonOxfordshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Kidlington Oxfordshire"
      description="Voice-optimized roofing services in Kidlington Oxfordshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Kidlington Oxfordshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceKidlingtonOxfordshire;
