import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceBeaconsfieldBuckinghamshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Beaconsfield Buckinghamshire"
      description="Voice-optimized roofing services in Beaconsfield Buckinghamshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Beaconsfield Buckinghamshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceBeaconsfieldBuckinghamshire;
