import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceRoseHillOxfordshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Rose Hill Oxfordshire"
      description="Voice-optimized roofing services in Rose Hill Oxfordshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Rose Hill Oxfordshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceRoseHillOxfordshire;
