import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceHaslemereSurrey: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Haslemere Surrey"
      description="Voice-optimized roofing services in Haslemere Surrey. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Haslemere Surrey"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceHaslemereSurrey;
