import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceLeatherheadSurrey: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Leatherhead Surrey"
      description="Voice-optimized roofing services in Leatherhead Surrey. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Leatherhead Surrey"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceLeatherheadSurrey;
