import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceMaidenheadBerkshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Maidenhead Berkshire"
      description="Voice-optimized roofing services in Maidenhead Berkshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Maidenhead Berkshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceMaidenheadBerkshire;
