import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceGerrardsCrossBuckinghamshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Gerrards Cross Buckinghamshire"
      description="Voice-optimized roofing services in Gerrards Cross Buckinghamshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Gerrards Cross Buckinghamshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceGerrardsCrossBuckinghamshire;
