import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceMidhurstWestSussex: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Midhurst West Sussex"
      description="Voice-optimized roofing services in Midhurst West Sussex. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Midhurst West Sussex"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceMidhurstWestSussex;
