import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInWokinghamBerkshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Wokingham Berkshire"
      description="Voice-optimized roof maintenance services in Wokingham Berkshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Wokingham Berkshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInWokinghamBerkshire;
