import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceBerkeleyGloucestershire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Berkeley Gloucestershire"
      description="Voice-optimized roofing services in Berkeley Gloucestershire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Berkeley Gloucestershire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceBerkeleyGloucestershire;
