import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceEastGrinsteadWestSussex: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in East Grinstead West Sussex"
      description="Voice-optimized roofing services in East Grinstead West Sussex. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="East Grinstead West Sussex"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceEastGrinsteadWestSussex;
