import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInWorthingWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Worthing West Sussex"
      description="Voice-optimized roof maintenance services in Worthing West Sussex. Use voice commands to get information, request quotes, and schedule appointments."
      location="Worthing West Sussex"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInWorthingWestSussex;
