import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInNewportPagnellBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Newport Pagnell Buckinghamshire"
      description="Voice-optimized roof maintenance services in Newport Pagnell Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Newport Pagnell Buckinghamshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInNewportPagnellBuckinghamshire;
