import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInWinslowBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Winslow Buckinghamshire"
      description="Voice-optimized roof installation services in Winslow Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Winslow Buckinghamshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInWinslowBuckinghamshire;
