import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInReigateSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Reigate Surrey"
      description="Voice-optimized roof installation services in Reigate Surrey. Use voice commands to get information, request quotes, and schedule appointments."
      location="Reigate Surrey"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInReigateSurrey;
