import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceTidworthWiltshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Tidworth Wiltshire"
      description="Voice-optimized roofing services in Tidworth Wiltshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Tidworth Wiltshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceTidworthWiltshire;
