import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInBeaconsfieldBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Beaconsfield Buckinghamshire"
      description="Voice-optimized roof maintenance services in Beaconsfield Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Beaconsfield Buckinghamshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInBeaconsfieldBuckinghamshire;
