import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInEsherSurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Esher Surrey"
      description="Voice-optimized roof inspection services in Esher Surrey. Use voice commands to get information, request quotes, and schedule appointments."
      location="Esher Surrey"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInEsherSurrey;
