import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceMiltonKeynesBuckinghamshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Milton Keynes Buckinghamshire"
      description="Voice-optimized roofing services in Milton Keynes Buckinghamshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Milton Keynes Buckinghamshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceMiltonKeynesBuckinghamshire;
