import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInThameOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Thame Oxfordshire"
      description="Voice-optimized roof installation services in Thame Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Thame Oxfordshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInThameOxfordshire;
