import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceRustingtonWestSussex: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Rustington West Sussex"
      description="Voice-optimized roofing services in Rustington West Sussex. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Rustington West Sussex"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceRustingtonWestSussex;
