import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceStonehouseGloucestershire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Stonehouse Gloucestershire"
      description="Voice-optimized roofing services in Stonehouse Gloucestershire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Stonehouse Gloucestershire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceStonehouseGloucestershire;
