import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInBlackbirdLeysOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Blackbird Leys Oxfordshire"
      description="Voice-optimized roof maintenance services in Blackbird Leys Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Blackbird Leys Oxfordshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInBlackbirdLeysOxfordshire;
