import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInGerrardsCrossBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Gerrards Cross Buckinghamshire"
      description="Voice-optimized roof maintenance services in Gerrards Cross Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Gerrards Cross Buckinghamshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInGerrardsCrossBuckinghamshire;
