import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceWokinghamBerkshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Wokingham Berkshire"
      description="Voice-optimized roofing services in Wokingham Berkshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Wokingham Berkshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceWokinghamBerkshire;
