import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInBurgessHillWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Burgess Hill West Sussex"
      description="Voice-optimized roof maintenance services in Burgess Hill West Sussex. Use voice commands to get information, request quotes, and schedule appointments."
      location="Burgess Hill West Sussex"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInBurgessHillWestSussex;
