import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoicePrincesRisboroughBuckinghamshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Princes Risborough Buckinghamshire"
      description="Voice-optimized roofing services in Princes Risborough Buckinghamshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Princes Risborough Buckinghamshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoicePrincesRisboroughBuckinghamshire;
