import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceNewportPagnellBuckinghamshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Newport Pagnell Buckinghamshire"
      description="Voice-optimized roofing services in Newport Pagnell Buckinghamshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Newport Pagnell Buckinghamshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceNewportPagnellBuckinghamshire;
