import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceBuckinghamBuckinghamshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Buckingham Buckinghamshire"
      description="Voice-optimized roofing services in Buckingham Buckinghamshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Buckingham Buckinghamshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceBuckinghamBuckinghamshire;
