import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInWinslowBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Winslow Buckinghamshire"
      description="Voice-optimized roof maintenance services in Winslow Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Winslow Buckinghamshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInWinslowBuckinghamshire;
