import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInEastGrinsteadWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in East Grinstead West Sussex"
      description="Voice-optimized roof installation services in East Grinstead West Sussex. Use voice commands to get information, request quotes, and schedule appointments."
      location="East Grinstead West Sussex"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInEastGrinsteadWestSussex;
