import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceWolvercoteOxfordshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Wolvercote Oxfordshire"
      description="Voice-optimized roofing services in Wolvercote Oxfordshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Wolvercote Oxfordshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceWolvercoteOxfordshire;
