import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceFleetHampshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Fleet Hampshire"
      description="Voice-optimized roofing services in Fleet Hampshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Fleet Hampshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceFleetHampshire;
