import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceBotleyOxfordshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Botley Oxfordshire"
      description="Voice-optimized roofing services in Botley Oxfordshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Botley Oxfordshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceBotleyOxfordshire;
