import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofMaintenanceInStonyStratfordBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Maintenance in Stony Stratford Buckinghamshire"
      description="Voice-optimized roof maintenance services in Stony Stratford Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Stony Stratford Buckinghamshire"
      service="Roof Maintenance"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofMaintenanceInStonyStratfordBuckinghamshire;
