import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInAmershamBuckinghamshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Amersham Buckinghamshire"
      description="Voice-optimized roof installation services in Amersham Buckinghamshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Amersham Buckinghamshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInAmershamBuckinghamshire;
