import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInAmesburyWiltshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Amesbury Wiltshire"
      description="Voice-optimized roof inspection services in Amesbury Wiltshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Amesbury Wiltshire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInAmesburyWiltshire;
