import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInRomseyHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Romsey Hampshire"
      description="Voice-optimized roof installation services in Romsey Hampshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Romsey Hampshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInRomseyHampshire;
