import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceRingwoodHampshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Ringwood Hampshire"
      description="Voice-optimized roofing services in Ringwood Hampshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Ringwood Hampshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceRingwoodHampshire;
