import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInPortsmouthHampshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Portsmouth Hampshire"
      description="Voice-optimized roof installation services in Portsmouth Hampshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Portsmouth Hampshire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInPortsmouthHampshire;
