import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInChippingNortonOxfordshire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Chipping Norton Oxfordshire"
      description="Voice-optimized roof inspection services in Chipping Norton Oxfordshire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Chipping Norton Oxfordshire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInChippingNortonOxfordshire;
