import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInChichesterWestSussex: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Chichester West Sussex"
      description="Voice-optimized roof inspection services in Chichester West Sussex. Use voice commands to get information, request quotes, and schedule appointments."
      location="Chichester West Sussex"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInChichesterWestSussex;
