import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceCowleyOxfordshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Cowley Oxfordshire"
      description="Voice-optimized roofing services in Cowley Oxfordshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Cowley Oxfordshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceCowleyOxfordshire;
