import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInstallationInGloucesterGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Installation in Gloucester Gloucestershire"
      description="Voice-optimized roof installation services in Gloucester Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Gloucester Gloucestershire"
      service="Roof Installation"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInstallationInGloucesterGloucestershire;
