import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInCamberleySurrey: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Camberley Surrey"
      description="Voice-optimized roof inspection services in Camberley Surrey. Use voice commands to get information, request quotes, and schedule appointments."
      location="Camberley Surrey"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInCamberleySurrey;
