import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceWendoverBuckinghamshire: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Wendover Buckinghamshire"
      description="Voice-optimized roofing services in Wendover Buckinghamshire. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Wendover Buckinghamshire"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceWendoverBuckinghamshire;
