import React from 'react';
import { NextPage } from 'next';
import LocationLayout from '@/components/LocationLayout';

const VoiceBognorRegisWestSussex: NextPage = () => {
  return (
    <LocationLayout
      title="Voice-Enabled Roofing Services in Bognor Regis West Sussex"
      description="Voice-optimized roofing services in Bognor Regis West Sussex. Use voice commands to find local roofers, get quotes, and schedule appointments."
      location="Bognor Regis West Sussex"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by LocationLayout */}
    </LocationLayout>
  );
};

export default VoiceBognorRegisWestSussex;
