import React from 'react';
import { NextPage } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

const VoiceRoofInspectionInGloucesterGloucestershire: NextPage = () => {
  return (
    <ServiceLayout
      title="Voice-Enabled Roof Inspection in Gloucester Gloucestershire"
      description="Voice-optimized roof inspection services in Gloucester Gloucestershire. Use voice commands to get information, request quotes, and schedule appointments."
      location="Gloucester Gloucestershire"
      service="Roof Inspection"
      voiceEnabled={true}
    >
      {/* Content will be dynamically generated by ServiceLayout */}
    </ServiceLayout>
  );
};

export default VoiceRoofInspectionInGloucesterGloucestershire;
